main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

project_name/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('trigger-1/', include('trigger_1.urls')),
    path('trigger-2/', include('trigger_2.urls')),
    path('trigger-3/', include('trigger_3.urls')),
    path('trigger-4/', include('trigger_4.urls')),
    path('trigger-5/', include('trigger_5.urls'))
]

trigger_1/urls.py
from django.urls import path

from . import views

app_name = 'trigger_1'

urlpatterns = [
    path('role/', views.role_view, name='role'),
    path('register/admin-satgas', views.register_admin_satgas_view, name='reg_admin_satgas'),
    path('register/admin-sistem', views.register_admin_sistem_view, name='reg_admin_sistem'),
    path('register/pengguna-publik', views.register_pengguna_publik_view, name='reg_pengguna_publik'),
    path('register/dokter', views.register_dokter_view, name='reg_dokter'),
    path('login/', views.halaman_login_view, name='halaman_login'),
    path('home/', views.login, name='home'),
    path('logout/', views.logout, name = 'logout'),
    path('pendaftaran-pasien/', views.pendaftaran_pasien, name = 'pendaftaran_pasien'),
    path('list-pasien/', views.list_pasien, name = 'list_pasien'),
    path('update-pasien/<str:nik>/<str:nama>/<str:id>', views.update_pasien, name = 'update_pasien'),
    path('delete-pasien/<str:nik>', views.delete_pasien, name = 'delete_pasien'),
    path('detail-pasien/<str:nik>', views.detail_pasien, name = 'detail_pasien'),
    
]

trigger_2/urls.py
from django.urls import path

from . import views

app_name = 'trigger_2'

urlpatterns = [
    path('lihat-jadwal-dokter/', views.lihat_jadwal_dokter, name='lihat_jadwal_dokter'),
    path('list-buat-jadwal-dokter/', views.list_buat_jadwal_dokter, name='list_buat_jadwal_dokter'),
    path('buat-jadwal/<str:kode_faskes>/<str:shift>/<str:tanggal>', views.buat_jadwal_dokter, name='buat_jadwal_dokter'),

    path('list-create-appointment/', views.list_create_appointment, name='list_create_appointment'),
    path('create-appointment/<str:nostr>/<str:username>/<str:kode_faskes>/<str:tgl_praktek>/<str:shift_praktek>', views.create_appointment, name='create_appointment'),
    path('read-appointment/', views.read_appointment, name='read_appointment'),
    path('delete-appointment/<str:nik>/<str:email_dokter>/<str:shift_praktek>/<str:tgl_praktek>/<str:kode_faskes>', views.delete_appointment, name='delete_appointment'),
    path('update-appointment/<str:nik>/<str:email_dokter>/<str:shift_praktek>/<str:tgl_praktek>/<str:kode_faskes>', views.update_appointment, name='update_appointment'),

    path('create-ruangan-rs/', views.create_ruangan_rs, name='create_ruangan_rs'),
    path('list-ruangan-rs/', views.list_ruangan_rs, name='list_ruangan_rs'),
    path('update-ruangan-rs/<str:koders>/<str:koderuangan>/<str:tipe>/<int:harga>', views.update_ruangan_rs, name='update_ruangan_rs'),
    path('create-bed-rs/', views.create_bed_rs, name='create_bed_rs'),
    path('list-bed-rs/', views.list_bed_rs, name='list_bed_rs'),
    path('delete-bed-rs/<str:koderuangan>/<str:koders>/<str:kodebed>', views.delete_bed_rs, name='delete_bed_rs'),
]

trigger_3/urls.py
from django.urls import path

from . import views

app_name = 'trigger_3'

urlpatterns = [
    path('buat-reservasi-rs/', views.create_reservasi_rs, name='buat_reservasi_rs'),
    path('list-reservasi-rs/', views.list_reservasi_rs, name='list_reservasi_rs'),
    path('delete-reservasi-rs/<str:kodepasien>/<str:tglmasuk>', views.delete_reservasi, name='delete-reservasi-rs'),
    path('update-reservasi-rs/<str:kodepasien>/<str:tglmasuk>', views.update_reservasi, name='update-reservasi-rs'),
    path('buat-faskes/', views.buat_faskes, name='buat-faskes'),
    path('list-faskes/', views.list_faskes, name='list-faskes'),
    path('delete-faskes/<str:kodefaskes>', views.delete_faskes, name='delete-faskes'),
    path('update-faskes/<str:kodefaskes>', views.update_faskes, name='update-faskes'),
    path('detail-faskes/<str:kodefaskes>', views.detail_faskes, name='detail-faskes'),
    path('buat-jadwal-faskes/', views.buat_jadwal_faskes, name='buat-jadwal-faskes'),
    path('list-jadwal-faskes/', views.list_jadwal_faskes, name='list-jadwal-faskes'),
    path('buat-rumah-sakit/', views.buat_rumah_sakit, name='buat-rumah-sakit'),
    path('list-rumah-sakit/', views.list_rumah_sakit, name='list-rumah-sakit'),
    path('update-rs/<str:kodefaskes>', views.update_rs, name='update-rs'),
    path('list-transaksi-rs/', views.list_transaksi_rs, name='list-transaksi-rs'),
    path('delete-transaksi-rs/<str:id>', views.delete_transaksi_rs, name='delete-transaksi-rs'),
    path('update-transaksi-rs/<str:id>', views.update_transaksi_rs, name='update-transaksi-rs'),

]

trigger_5/urls.py
from django.urls import path

from . import views

app_name = 'trigger_5'

urlpatterns = [
    path('lihat-transaksi-makan/', views.lihat_transaksi_makan, name='lihat_transaksi_makan'),
    path('lihat-paket-makan/', views.lihat_paket_makan, name='lihat_paket_makan'),
    path('lihat-hotel/', views.lihat_hotel, name='lihat_hotel'),
    path('lihat-transaksi-makan-detail/<str:idtransaksi>/<str:idtransaksimakan>', views.lihat_transaksi_makan_detail, name='lihat_transaksi_makan_detail'),
    path('buat-paket-makan/', views.buat_paket_makan, name='buat_paket_makan'),
    path('buat-hotel/', views.buat_hotel, name='buat_hotel'),
    path('delete-paket-makan/<str:kodehotel>/<str:kodepaket>', views.delete_paket_makan, name='delete_paket_makan'),
    path('update-paket-makan/<str:kodehotel>/<str:kodepaket>', views.update_paket_makan, name='update_paket_makan'),

    path('delete-transaksi-makan/<str:idtransaksi>/<str:idtransaksimakan>', views.delete_transaksi_makan, name='delete_transaksi_makan'),
    path('update-hotel/<str:kode>', views.update_hotel, name='update_hotel'),
]

trigger_1/models.py
from django.db import models

# Create your models here.

trigger_1/views.py
from django.shortcuts import render, reverse, redirect
from .forms import *
from django.db import connection
from collections import namedtuple
from django.http import HttpResponseRedirect
from django.db import IntegrityError, InternalError

def namedtuplefetchall(cursor):
    "Return all rows from a cursor as a namedtuple"
    desc = cursor.description
    nt_result = namedtuple('Result', [col[0] for col in desc])
    return [nt_result(*row) for row in cursor.fetchall()]

def role_view(request):
    return render(request, 'trigger_1/role.html')

def register_pengguna_publik_view(request, pesan=''):
    if request.method == "POST":
        formulir = PenggunaPublikForm(request.POST)
        email = str(request.POST['email'])
        password = str(request.POST['password'])
        nama = str(request.POST['nama'])
        nik = str(request.POST['nik'])
        no_hp = str(request.POST['no_hp'])

        try:
            cursor = connection.cursor()
            cursor.execute("set search_path to siruco")
            cursor.execute("insert into akun_pengguna values ('"+email+ "','" +password+ "','Pengguna_publik')")
            cursor.execute("insert into pengguna_publik values ('"+email+"','"+nik+"','"+nama+"', 'AKTIF' ,'Pengguna_publik','"+no_hp+"')")
            cursor.execute("set search_path to public")
            cursor.close()
            login(request,email,password)
            return redirect('trigger_1:home')

        except InternalError:
            print("masuk sini ga")
            pesan = 'Password Anda belum memenuhi syarat, silahkan pastikan bahwa password minimal terdapat 1 huruf kapital dan 1 angka'
            formulir = PenggunaPublikForm()
            argument = {    
                'pesan' : pesan,
                'formPenggunaPublik' : formulir,
            }
            
            return render(request, 'trigger_1/register-pengguna-publik.html', argument)

    else:
        formulir = PenggunaPublikForm()

    
        argument = {
            'formPenggunaPublik' : formulir,
            }
    return render(request, 'trigger_1/register-pengguna-publik.html', argument)


def register_dokter_view(request, pesan = ''):
    if request.method == "POST":
        formulir = DokterForm(request.POST)

        email = str(request.POST['email'])
        password = str(request.POST['password'])
        no_str = str(request.POST['no_str'])
        nama = str(request.POST['nama'])
        no_hp = str(request.POST['no_hp'])
        gelar_depan = str(request.POST['gelar_depan'])
        gelar_belakang = str(request.POST['gelar_belakang'])
        
        try:
            cursor = connection.cursor()
            cursor.execute("set search_path to siruco")
            cursor.execute("insert into akun_pengguna values ('"+email+ "','" +password+ "','Dokter')") 
            cursor.execute("insert into admin values ('"+email+ "')") # foreign key ke admin
            cursor.execute("insert into dokter values ('"+email+"','"+no_str+"','"+nama+"', '"+no_hp+"' ,'"+gelar_depan+"','"+gelar_belakang+"')")
            cursor.execute("set search_path to public")
            cursor.close()
            login(request,email,password)
            return redirect('trigger_1:home')

        except InternalError:
            print("masuk sini ga")
            pesan = 'Password Anda belum memenuhi syarat, silahkan pastikan bahwa password minimal terdapat 1 huruf kapital dan 1 angka'
            formulir = DokterForm()
            argument = {    
                'pesan' : pesan,
                'formDokter' : formulir,
            }
            
            return render(request, 'trigger_1/register-dokter.html', argument)

    else:
        formulir = DokterForm()

        argument = {    
            'formDokter' : formulir,
            'pesan':pesan,
        }

    return render(request, 'trigger_1/register-dokter.html', argument)

def register_admin_sistem_view(request):
    if request.method == "POST":
        formulir = AdminSistemForm(request.POST)

        email = str(request.POST['email'])
        password = str(request.POST['password'])    
        try:    
            cursor = connection.cursor()
            cursor.execute("set search_path to siruco")
            cursor.execute("insert into akun_pengguna values ('"+email+ "','" +password+ "','Admin_sistem')") 
            cursor.execute("insert into admin values ('"+email+ "')") # foreign key ke admin
            cursor.execute("set search_path to public")
            cursor.close()
            login(request,email,password)
            return redirect('trigger_1:home')
        except InternalError:
            pesan = 'Password Anda belum memenuhi syarat, silahkan pastikan bahwa password minimal terdapat 1 huruf kapital dan 1 angka'
            formulir = AdminSistemForm()
            argument = {    
                'pesan' : pesan,
                'formAdminSistem' : formulir,
            }
            
            return render(request, 'trigger_1/register-admin-sistem.html', argument)

    else:
        formulir = AdminSistemForm()

        argument = {    
            'formAdminSistem' : formulir,
        }

    return render(request, 'trigger_1/register-admin-sistem.html', argument)

def register_admin_satgas_view(request):
   
    cursor = connection.cursor()
    cursor.execute("set search_path to siruco")
    cursor.execute("select * from faskes") 
    hasil = namedtuplefetchall(cursor)
    kode_faskes = []
    for x in range (len(hasil)):
        kode_faskes.append(hasil[x].kode)

    cursor.execute("set search_path to public")
    cursor.close()


    if request.method == "POST":
        formulir = AdminSatgasForm(request.POST)

        email = str(request.POST['email'])
        password = str(request.POST['password'])
        idfaskes = str(request.POST['kode_faskes'])

        try:
            cursor = connection.cursor()
            cursor.execute("set search_path to siruco")
            cursor.execute("insert into akun_pengguna values ('"+email+ "','" +password+ "','Admin_satgas')") 
            cursor.execute("insert into admin values ('"+email+ "')") # foreign key ke admin
            cursor.execute("insert into admin_satgas values ('"+email+ "','" +idfaskes+ "')") # foreign key ke admin
            cursor.execute("set search_path to public")
            cursor.close()
            login(request,email,password)
            return redirect('trigger_1:home')
            
        except InternalError:
            pesan = 'Password Anda belum memenuhi syarat, silahkan pastikan bahwa password minimal terdapat 1 huruf kapital dan 1 angka'
            formulir = AdminSatgasForm()
            argument = {    
                'pesan' : pesan,
                'formAdminSatgas' : formulir,
                'kode_faskes' : kode_faskes,
            }
            
            return render(request, 'trigger_1/register-admin-satgas.html', argument)


    else:
        formulir = AdminSatgasForm()
        argument = {    
            'formAdminSatgas' : formulir,
            'kode_faskes' : kode_faskes,
        }
    
    return render(request, 'trigger_1/register-admin-satgas.html', argument)

def halaman_login_view(request, pesan=''):
    try:
        email = request.session['email']
        return login(request)
        
    except KeyError:
        formulir = FormLogin()
        # JANGAN LUPA DIAPUS
        cursor = connection.cursor()
        cursor.execute("set search_path to siruco")
        cursor.execute("select * from akun_pengguna")
        hasil = namedtuplefetchall(cursor)
        cursor.execute("set search_path to public")
        cursor.close()
        argument = {
            'formlogin' : formulir,
            'table' : hasil,
            'pesan' : pesan,
        }
        return render(request, 'trigger_1/login.html', argument)

def login(request,email=None,Password=None):
    try:
        email = request.session['email']
        password = request.session['password']
    except:
        email = request.POST.get('email', False)
        password = request.POST.get('password', False)
        
    email = str(email)
    password = str(password)
    cursor = connection.cursor()
    cursor.execute("set search_path to siruco")
    cursor.execute("select * from akun_pengguna where username='"+email+"' and password='"+password+"'")
    
    hasil = namedtuplefetchall(cursor)

    if (hasil == []):
        cursor.execute("set search_path to public")
        cursor.close()
        pesan = "Maaf Username atau Password salah"
        argument = {
            'pesan' : pesan,
        } 
        return halaman_login_view(request, argument) #nangkep error

    peran = hasil[0].peran
    print(peran)
    
    cursor.execute("set search_path to public")
    request.session['email'] = email
    request.session['password'] = password
    request.session.set_expiry(1800)
    request.session['peran'] = hasil[0].peran

    cursor.execute("set search_path to siruco")
    
    if (peran == "Admin_sistem"):
        cursor.execute("select * from akun_pengguna where username='"+email+"'")
        hasil = namedtuplefetchall(cursor)
        profil = hasil[0]
        argument = {
            'profil' : profil,
            'peran' : peran
        }
        cursor.execute("set search_path to public")
        cursor.close()
        return render(request,'profil-admin-sistem.html', argument)
        
    elif (peran == "Pengguna_publik"):
        cursor.execute("select * from pengguna_publik where username='"+email+"'")
        hasil = namedtuplefetchall(cursor)
        profil = hasil[0]
        argument = {
            'profil' : profil,
            'peran' : peran,
            'password' : password
        }
        print(argument)
        cursor.execute("set search_path to public")
        cursor.close()
        
        return render(request,'profil-pengguna-publik.html', argument)

    elif (peran == "Dokter"):

trigger_1/templates/base-dokter.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="icon" href="{% static 'main/asset/s_icon.svg' %}" type="image/x-icon">
    
    <title>SIRUCO</title>
    {% block meta %}
    {% endblock %}

</head>
<body id="body">
    <nav>
        <a href = "/trigger-1/home"><img src="{% static 'main/asset/siruco_logo.svg' %}"></a>
        <div class="navbar">

          <div class="dropdown">
            <button class="dropbtn">Pasien 
              <i class="fa fa-caret-down"></i>
            </button>
            <div class="dropdown-content">
              <a href="{% url 'trigger_2:read_appointment' %}">List Appointment</a>
              <a href="#">Buat Hasil Tes Pasien</a>
              <a href="#">List Hasil Tes Pasien</a>
            </div>
        </div> 

        <div class="dropdown">
            <button class="dropbtn">Rumah Sakit
              <i class="fa fa-caret-down"></i>
            </button>
            <div class="dropdown-content">
              <a href="{% url 'trigger_2:list_buat_jadwal_dokter' %}">Buat Jadwal Dokter</a>
              <a href="{% url 'trigger_2:lihat_jadwal_dokter' %}">List Jadwal Dokter</a>
            </div>
        </div> 
        
      </div>
        
      <a href="/trigger-1/logout"><h3 style="color:#507DBC; background-color: #cfddec;">Logout</h3></a>
    </nav>
    {% block content %}
    
    {% endblock content %}  
</body>
</html>

trigger_1/templates/base-pengguna-publik.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="icon" href="{% static 'main/asset/s_icon.svg' %}" type="image/x-icon">
    
    <title>SIRUCO</title>
    {% block meta %}
    {% endblock %}

</head>
<body id="body">
    <nav>
        <a href = "/trigger-1/home"><img src="{% static 'main/asset/siruco_logo.svg' %}"></a>
        <div class="navbar">

          <div class="dropdown">
            <button class="dropbtn">Pasien 
              <i class="fa fa-caret-down"></i>
            </button>
            <div class="dropdown-content">
              <a href="/trigger-1/pendaftaran-pasien">Pendaftaran Pasien</a>
              <a href="/trigger-1/list-pasien">List Pasien</a>
              <a href="{% url 'trigger_2:list_create_appointment' %}">Buat Appointment</a>
              <a href="{% url 'trigger_2:read_appointment' %}">List Appointment</a>
              <a href="#">List Hasil Tes Pasien</a>
            </div>
        </div> 

        <div class="dropdown">
            <button class="dropbtn">Rumah Sakit 
              <i class="fa fa-caret-down"></i>
            </button>
            <div class="dropdown-content">
              <a href="{% url 'trigger_2:lihat_jadwal_dokter' %}">List Jadwal Dokter</a>
              <a href="{% url 'trigger_3:list_reservasi_rs' %}">List Reservasi RS</a>
            </div>
        </div> 
        
        <div class="dropdown">
            <button class="dropbtn">Hotel 
              <i class="fa fa-caret-down"></i>
            </button>
            <div class="dropdown-content">
              <a href="{% url 'trigger_5:lihat_hotel' %}">List Hotel</a>
              <a href="/trigger-4/list-ruangan-hotel-viewonly/">List Ruangan Hotel</a>
              <a href="{% url 'trigger_5:lihat_paket_makan' %}">List Paket Makan</a>
              <a href="/trigger-4/buat-reservasi-hotel/">Buat Reservasi Hotel</a>
              <a href="/trigger-4/list-reservasi-hotel/">List Reservasi Hotel</a>
            </div>
        </div> 
        <div class="dropdown">
            <button class="dropbtn">Transaksi 
              <i class="fa fa-caret-down"></i>
            </button>
            <div class="dropdown-content">
              <a href="#">Bayar Transaksi RS</a>
              <a href="#">Bayar Transaksi Hotel</a>
              <a href="/trigger-4/list-transaksi-booking-hotel/">List Transaksi Booking Hotel</a>
              <a href="#">Buat Transaksi Makan dan Daftar Pesan</a>
              <a href="{% url 'trigger_5:lihat_transaksi_makan' %}">List Transaksi Makan dan Daftar Pesan</a>
            </div>
        </div> 
      </div>
        
      <a href="/trigger-1/logout"><h3 style="color:#507DBC; background-color: #cfddec;">Logout</h3></a>
    </nav>
    {% block content %}
    
    {% endblock content %}  
</body>
</html>

trigger_1/templates/base-satgas.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="icon" href="{% static 'main/asset/s_icon.svg' %}" type="image/x-icon">
    
    <title>SIRUCO</title>
    {% block meta %}
    {% endblock %}

</head>
<body id="body">
    <nav>
        <a href = "/trigger-1/home"><img src="{% static 'main/asset/siruco_logo.svg' %}"></a>
        <div class="navbar">

          <div class="dropdown">
            <button class="dropbtn">Pasien 
              <i class="fa fa-caret-down"></i>
            </button>
            <div class="dropdown-content">
              <a href="{% url 'trigger_2:list_create_appointment' %}">Buat Appointment</a>
              <a href="{% url 'trigger_2:read_appointment' %}">List Appointment</a>
              <a href="#">List Hasil Tes Pasien</a>
            </div>
        </div> 

        <div class="dropdown">
            <button class="dropbtn">Faskes 
              <i class="fa fa-caret-down"></i>
            </button>
            <div class="dropdown-content">
              <a href="{% url 'trigger_3:buat-faskes' %}">Buat Faskes</a>
              <a href="{% url 'trigger_3:list-faskes' %}">List Faskes</a>
              <a href="{% url 'trigger_3:buat-jadwal-faskes' %}">Buat Jadwal Faskes</a>
              <a href="{% url 'trigger_3:list-jadwal-faskes' %}">List Jadwal Faskes</a>
            </div>
        </div> 
        
        <div class="dropdown">
            <button class="dropbtn">Rumah Sakit 
              <i class="fa fa-caret-down"></i>
            </button>
            <div class="dropdown-content">
              <a href="{% url 'trigger_3:buat-rumah-sakit' %}">Buat RS</a>
              <a href="{% url 'trigger_3:list-rumah-sakit' %}">List RS</a>
              <a href="{% url 'trigger_2:lihat_jadwal_dokter' %}">List Jadwal Dokter</a>
              <a href="{% url 'trigger_2:create_ruangan_rs' %}">Buat Ruangan RS</a>
              <a href="{% url 'trigger_2:list_ruangan_rs' %}">List Ruangan RS</a>
              <a href="{% url 'trigger_2:create_bed_rs' %}">Buat Bed RS</a>
              <a href="{% url 'trigger_2:list_bed_rs' %}">List Bed RS</a>
              <a href="{% url 'trigger_3:buat_reservasi_rs' %}">Buat Reservasi RS</a>
              <a href="{% url 'trigger_3:list_reservasi_rs' %}">List Reservasi RS</a>
            </div>
        </div> 
        <div class="dropdown">
            <button class="dropbtn">Hotel 
              <i class="fa fa-caret-down"></i>
            </button>
            <div class="dropdown-content">
              <a href="{% url 'trigger_5:lihat_hotel' %}">List Hotel</a>
              <a href="/trigger-4/list-ruangan-hotel-viewonly/">List Ruangan Hotel</a>
              <a href="{% url 'trigger_5:lihat_paket_makan' %}">List Paket Makan</a>
              <a href="/trigger-4/buat-reservasi-hotel/">Buat Reservasi Hotel</a>
              <a href="/trigger-4/list-reservasi-hotel/">List Reservasi Hotel</a>
            </div>
        </div> 

        <div class="dropdown">
            <button class="dropbtn">Transaksi 
              <i class="fa fa-caret-down"></i>
            </button>
            <div class="dropdown-content">
              <a href="{% url 'trigger_3:list-transaksi-rs' %}">List Transaksi RS</a>
              <a href="/trigger-4/list-transaksi-hotel/">List Transaksi Hotel</a>
              <a href="/trigger-4/list-transaksi-booking-hotel/">List Transaksi Booking Hotel</a>
              <a href="#">Buat Transaksi Makan dan Daftar Pesan</a>
              <a href="{% url 'trigger_5:lihat_transaksi_makan' %}">List Transaksi Makan dan Daftar Pesan</a>
            </div>
        </div> 

      </div>
        
      <a href="/trigger-1/logout"><h3 style="color:#507DBC; background-color: #cfddec;">Logout</h3></a>
    </nav>
    {% block content %}
    
    {% endblock content %}  
</body>
</html>

trigger_1/templates/base-sistem.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="icon" href="{% static 'main/asset/s_icon.svg' %}" type="image/x-icon">
    
    <title>SIRUCO</title>
    {% block meta %}
    {% endblock %}

</head>
<body id="body">
    <nav>
        <a href = "/trigger-1/home"><img src="{% static 'main/asset/siruco_logo.svg' %}"></a>
        <div class="navbar">

          <div class="dropdown">
            <button class="dropbtn">Hotel  
              <i class="fa fa-caret-down"></i>
            </button>
            <div class="dropdown-content">
              <a href="{% url 'trigger_5:buat_hotel' %}">Buat Hotel</a>
              <a href="{% url 'trigger_5:lihat_hotel' %}">List Hotel</a>
              <a href="/trigger-4/pendaftaran-ruangan-hotel/">Buat Ruangan Hotel</a>
              <a href="/trigger-4/list-ruangan-hotel/">List Ruangan Hotel</a>
              <a href="{% url 'trigger_5:buat_paket_makan' %}">Buat Paket Makan</a>
              <a href="{% url 'trigger_5:lihat_paket_makan' %}">List Paket Makan</a>
            </div>
        </div> 

      </div>
        
        <a href="/trigger-1/logout"><h3 style="color:#507DBC; background-color: #cfddec;">Logout</h3></a>
    </nav>
    {% block content %}
    
    {% endblock content %}  
</body>
</html>

trigger_1/templates/profil-admin-satgas.html
{% extends 'base-satgas.html' %}
{% load static %}

{% block meta %}
<link rel="stylesheet" href="{% static 'css/trigger_1.css' %}">
<link rel="stylesheet" href="{% static 'main/css/home.css' %}">

{% endblock %}


{% block content %}



<br><br><br><br>
<h2 class="tengah">{{ profil.username }}'s Profile as Admin Satgas</h2><br>
  <table>
    <tr>
      <td><h3>
        Peran
      </h3></td>
      <td><p> 
        {{ peran }}
      </p></td>
    </tr>

    <tr>
        <td><h3>
          Username
        </h3></td>
        <td><p> 
          {{ profil.username }}
        </p></td>
    </tr>
    <tr>
        <td><h3>
          Password
        </h2></td>
        <td><p> 
          {{ profil.password }}
        </p></td>
    </tr>
    <tr>
        <td><h3>
          ID Faskes
        </h2></td>
        <td><p> 
          {{ adminsatgas.idfaskes }}
        </p></td>
    </tr>
  
</table>




{% endblock %}