main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

project_name/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('trigger-1/', include('trigger_1.urls')),
    path('trigger-2/', include('trigger_2.urls')),
    path('trigger-3/', include('trigger_3.urls')),
    path('trigger-4/', include('trigger_4.urls')),
    path('trigger-5/', include('trigger_5.urls'))
]

trigger_5/urls.py
from django.urls import path

from . import views

app_name = 'trigger_5'

urlpatterns = [
    path('lihat-transaksi-makan/', views.lihat_transaksi_makan, name='lihat_transaksi_makan'),
    path('lihat-paket-makan/', views.lihat_paket_makan, name='lihat_paket_makan'),
    path('lihat-hotel/', views.lihat_hotel, name='lihat_hotel'),
    path('lihat-transaksi-makan-detail/<str:idtransaksi>/<str:idtransaksimakan>', views.lihat_transaksi_makan_detail, name='lihat_transaksi_makan_detail'),
    path('buat-paket-makan/', views.buat_paket_makan, name='buat_paket_makan'),
    path('buat-hotel/', views.buat_hotel, name='buat_hotel'),
    path('delete-paket-makan/<str:kodehotel>/<str:kodepaket>', views.delete_paket_makan, name='delete_paket_makan'),
    path('update-paket-makan/<str:kodehotel>/<str:kodepaket>', views.update_paket_makan, name='update_paket_makan'),

    path('delete-transaksi-makan/<str:idtransaksi>/<str:idtransaksimakan>', views.delete_transaksi_makan, name='delete_transaksi_makan'),
    path('update-hotel/<str:kode>', views.update_hotel, name='update_hotel'),
]

trigger_5/models.py
from django.db import models

# Create your models here.

trigger_5/forms.py
from django import forms

class PaketMakanForm(forms.Form):
    # kode_hotel = forms.CharField(max_length=5, required=True) 
    kode_paket = forms.CharField(max_length=5, required=True)
    nama_paket = forms.CharField(max_length=20, required=True)
    harga = forms.IntegerField(required=True)

class BuatHotelForm(forms.Form):
    # kode_hotel = forms.CharField(max_length=5, required=True) 
    nama_hotel = forms.CharField(max_length=30, required=True)
    jalan = forms.CharField(max_length=30, required=True)
    kelurahan = forms.CharField(max_length=30, required=True)
    kecamatan = forms.CharField(max_length=30, required=True)
    kabkot = forms.CharField(max_length=30, required=True)
    prov = forms.CharField(max_length=30, required=True)
    rujukan = forms.BooleanField(required=False)

class UpdatePaketMakan(forms.Form):
    nama_paket = forms.CharField(max_length=20, required=True)
    harga = forms.IntegerField(required=True)

trigger_5/views.py
from django.shortcuts import render, reverse, redirect
from .forms import *
from django.db import connection
from collections import namedtuple
from django.http import HttpResponseRedirect
from django.db import IntegrityError, InternalError
from collections import namedtuple
from json import dumps
import datetime

def namedtuplefetchall(cursor):
    "Return all rows from a cursor as a namedtuple"
    desc = cursor.description
    nt_result = namedtuple('Result', [col[0] for col in desc])
    return [nt_result(*row) for row in cursor.fetchall()]

def dictfetchall(cursor):
    "Return all rows from a cursor as a dict"
    columns = [col[0] for col in cursor.description]
    return [
        dict(zip(columns, row))
        for row in cursor.fetchall()
    ]

def lihat_transaksi_makan(request):
    email = request.session['email']
    password = request.session['password']
    cursor = connection.cursor()
    cursor.execute("set search_path to siruco")
    cursor.execute("select * from transaksi_makan natural join transaksi_hotel")
    lunas = namedtuplefetchall(cursor)
    cursor.execute("select * from akun_pengguna where username='"+email+"' and password='"+password+"'")
    hasil1 = namedtuplefetchall(cursor)
    peran = hasil1[0].peran
    cursor.execute("set search_path to public")
    cursor.close()
    argument = {
            'table':lunas,
        }
    if (peran == "Admin_satgas"):
        
        return render(request, 'trigger_5/lihat-transaksi-makan-satgas.html', argument)
    elif (peran == "Pengguna_publik"):
        return render(request, 'trigger_5/lihat-transaksi-makan.html', argument)

def lihat_paket_makan(request):
    email = request.session['email']
    password = request.session['password']
    cursor = connection.cursor()
    cursor.execute("set search_path to siruco")
    cursor.execute("select * from paket_makan")
    hasil = namedtuplefetchall(cursor)
    cursor.execute("select * from akun_pengguna where username='"+email+"' and password='"+password+"'")
    hasil1 = namedtuplefetchall(cursor)
    peran = hasil1[0].peran
    cursor.execute("set search_path to public")
    cursor.close()
    argument = {
            'table':hasil,
        }
    if (peran == "Admin_satgas"):
        return render(request, 'trigger_5/lihat-paket-makan-satgas.html', argument)
    elif (peran == "Pengguna_publik"):
        return render(request, 'trigger_5/lihat-paket-makan.html', argument)
    elif (peran == "Admin_sistem"):
        return render(request, 'trigger_5/lihat-paket-makan-sistem.html', argument)

def lihat_hotel(request):
    email = request.session['email']
    password = request.session['password']
    cursor = connection.cursor()
    cursor.execute("set search_path to siruco")
    cursor.execute("select * from hotel")
    hasil = namedtuplefetchall(cursor)
    cursor.execute("select * from akun_pengguna where username='"+email+"' and password='"+password+"'")
    hasil1 = namedtuplefetchall(cursor)
    peran = hasil1[0].peran
    cursor.execute("set search_path to public")
    cursor.close()
    argument = {
            'table':hasil,
        }
    if (peran == "Admin_satgas"):
        return render(request, 'trigger_5/lihat-hotel-satgas.html', argument)
    elif (peran == "Pengguna_publik"):
        return render(request, 'trigger_5/lihat-hotel.html', argument)
    elif (peran == "Admin_sistem"):
        return render(request, 'trigger_5/lihat-hotel-sistem.html', argument)

def lihat_transaksi_makan_detail(request,idtransaksi,idtransaksimakan):
    email = request.session['email']
    password = request.session['password']
    cursor = connection.cursor()
    cursor.execute("set search_path to siruco")
    cursor.execute("select * from daftar_pesan natural join paket_makan where id_transaksi ='"+idtransaksi+"' and idtransaksimakan = '"+idtransaksimakan+"'")
    hasil = namedtuplefetchall(cursor)
    cursor.execute("select * from akun_pengguna where username='"+email+"' and password='"+password+"'")
    hasil1 = namedtuplefetchall(cursor)
    peran = hasil1[0].peran
    idtransaksi = hasil[0].id_transaksi
    idtransaksimakan = hasil[0].idtransaksimakan
    kodehotel = hasil[0].kodehotel
    cursor.execute("select * from transaksi_hotel where idtransaksi='"+idtransaksi+"'")
    hasil3 = namedtuplefetchall(cursor)
    totalbayar = hasil3[0].totalbayar
    print(hasil)
    cursor.execute("set search_path to public")
    cursor.close()
    argument = {
            'table':hasil,
            'idtransaksi':idtransaksi,
            'idtransaksimakan':idtransaksimakan,
            'kodehotel':kodehotel,
            'totalbayar':totalbayar,
        }
    if (peran == "Admin_satgas"):
        return render(request, 'trigger_5/lihat-transaksi-makan-detail.html', argument)
    elif (peran == "Pengguna_publik"):
        return render(request, 'trigger_5/lihat-transaksi-makan-detail.html', argument)

def buat_paket_makan(request):
    if request.method == "POST": 
        formulir = PaketMakanForm(request.POST) 
        kode_hotel = str(request.POST['kode_hotel'])
        kode_paket = str(request.POST['kode_paket'])
        nama_paket = str(request.POST['nama_paket'])
        harga = str(request.POST['harga'])
        cursor = connection.cursor()
        cursor.execute("set search_path to siruco")
        cursor.execute("insert into paket_makan values ('"+kode_hotel+ "','" +kode_paket+"', '"+nama_paket+"', '"+harga+"')") 
        cursor.execute("set search_path to public")
        cursor.close()
        return redirect('trigger_5:lihat_paket_makan')
    else:
        formulir = PaketMakanForm()
        cursor = connection.cursor()
        cursor.execute("set search_path to siruco")
        cursor.execute("select * from hotel") 
        hasil = namedtuplefetchall(cursor)
        kode_hotel = []
        for x in range (len(hasil)):
            kode_hotel.append(hasil[x].kode)
        print("==========")
        print(kode_hotel)
        cursor.execute("set search_path to public")
        cursor.close()
        argument = {    
            'form' : formulir,
            'kode_hotel' : kode_hotel,
        }
    return render(request, 'trigger_5/buat-paket-makan.html', argument)

def buat_hotel(request):
    if request.method == "POST": 
        
        
        form = BuatHotelForm(request.POST)
        if form.is_valid():
            rujukan = form.cleaned_data['rujukan']
        if rujukan == True:
            rujukan = '1'

        else:
            rujukan='0'
        print(rujukan)
        nama_hotel = str(request.POST['nama_hotel'])
        jalan = str(request.POST['jalan'])
        kelurahan = str(request.POST['kelurahan'])
        kecamatan = str(request.POST['kecamatan'])
        kabkot = str(request.POST['kabkot'])
        prov = str(request.POST['prov'])
        cursor = connection.cursor()
        cursor.execute("set search_path to siruco")
        cursor.execute("select count(kode) from hotel")
        hasil1 = namedtuplefetchall(cursor)
        kode = str(hasil1[0].count)
        print(kode)
        cursor.execute("insert into hotel values ('H"+kode+ "','"+nama_hotel+ "','" +rujukan+"', '"+jalan+"', '"+kelurahan+"', '"+kecamatan+"', '"+kabkot+"', '"+prov+"')") 
        cursor.execute("set search_path to public")
        cursor.close()
        return redirect('trigger_5:lihat_hotel')
    else:
        formulir = BuatHotelForm()
        cursor = connection.cursor()
        argument = {    
            'form' : formulir,
        }
    return render(request, 'trigger_5/buat-hotel.html', argument)

def delete_paket_makan(request, kodehotel, kodepaket):
    cursor = connection.cursor()
    cursor.execute("set search_path to siruco")
    cursor.execute("delete from paket_makan where kodehotel='"+ kodehotel +"' AND kodepaket='"+ kodepaket +"'")
    cursor.execute("set search_path to public")
    cursor.close()
    return redirect('trigger_5:lihat_paket_makan')

def update_paket_makan(request, kodehotel, kodepaket):
    if request.method == "POST":
         
        nama_paket = str(request.POST['nama_paket']) 
        harga = str(request.POST['harga'])
        
        with connection.cursor() as c:
            c.execute("""UPDATE SIRUCO.paket_makan SET nama =  %s, harga =  %s
                             WHERE kodehotel = %s and  kodepaket = %s""",
                                [nama_paket, harga, kodehotel, kodepaket]
            )
        
            
        return HttpResponseRedirect(reverse('trigger_5:lihat_paket_makan'))

    else:
        cursor = connection.cursor()
        cursor.execute("set search_path to siruco")
        cursor.execute("select * from paket_makan where kodehotel = '" +kodehotel+"' and kodepaket = '" +kodepaket+"'")
        hasil = namedtuplefetchall(cursor)
        paketmakan = hasil[0]
        cursor.execute("set search_path to public")
        cursor.close()

        data_awal = {
            'nama_paket': paketmakan[2],
            'harga': paketmakan[3],
          
        }
        form_update_paket_makan = UpdatePaketMakan(initial = data_awal)

        argument = {    
        'updatepaketmakan' : form_update_paket_makan,
        'paketmakan' : paketmakan,
        }
        return render(request, 'trigger_5/update-paket-makan.html', argument)

def delete_transaksi_makan(request, idtransaksi, idtransaksimakan):
    cursor = connection.cursor()
    cursor.execute("set search_path to siruco")
    cursor.execute("delete from transaksi_makan where idtransaksi='"+ idtransaksi +"' AND idtransaksimakan='"+ idtransaksimakan +"'")
    cursor.execute("set search_path to public")
    cursor.close()
    return redirect('trigger_5:lihat_transaksi_makan')

def update_hotel(request, kode):
    if request.method == "POST": 
        form = BuatHotelForm(request.POST)
        if form.is_valid():
            rujukan = form.cleaned_data['rujukan']
        if rujukan == True:
            rujukan = '1'

        else:
            rujukan='0'
            

trigger_5/templates/trigger_5/buat-hotel.html
{% extends 'base-sistem.html' %}
{% load static %}

{% block meta %}
<link rel="stylesheet" href="{% static 'css/trigger_1.css' %}">
<link rel="stylesheet" href="{% static 'main/css/home.css' %}">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
{% endblock %}


{% block content %}

<script language="javascript" type="text/javascript">
  
  $(document).ready(function () {

    $("#kode_hotel").change(function () {
        var el = $(this);
        var data = JSON.parse("{{data|escapejs}}");  //ngambil data yang di transfer dari views supaya bisa dipake gi js

        var list = document.getElementById("kode_ruangan"); //clear data sebelumnya
        while (list.hasChildNodes()) {
          list.removeChild(list.firstChild);
        }

        const keys = Object.keys(data); // ngambil key-key yang ada dalam bentuk list
        for (i = 0; i < keys.length; i++) {
          if (el.val() == keys[i]) {   
            var temp = data[keys[i]]; //list dari kode room
            for (j = 0; j < temp.length ; j++) {  //masukin optionnya
              $("#kode_ruangan").append("<option>"+temp[j]+"</option>");
              
            }break;
          }
         
        }
        
       
    });

    });

    function Validation()
    {
      var entrydate, outdate;
      entrydate = document.getElementById("id_tanggal_masuk").value;
      outdate = document.getElementById("id_tanggal_keluar").value;
      if(entrydate > outdate)
      
      {
          event.preventDefault();
          alert("Maaf, tolong masukan tanggal keluar > tanggal masuk");
          returnToPreviousPage();
          return false;
      }
      return true;
    }
 
  </script>

<br><br><br><br>
<section class="home">
    <section class="section2">
        <div class="parent-card">
            <div class="box-card">
              <h2 class="title">FORM BUAT HOTEL</h2><br>
                          
              <form method="POST" action="{% url 'trigger_5:buat_hotel' %}"  onsubmit="Validation();">
                {% csrf_token %}

                  <div class="row">
                    <div class="col-25">
                      <label for="jenis_bed">
                        Kode Hotel
                      </label>
                    </div>
                    <div class="col-75">
                        <input for='kode_hotel' id ='kode_hotel' value="XXX" disabled></input>
                    </div>
                  </div>
                
                  <div class="row">
                    <div class="col-25">
                      <label for="tanggal_keluar">
                        Nama Hotel
                      </label>
                    </div>
                    <div class="col-75">
                      {{ form.nama_hotel }}
                    </div>
                  </div> 
                    <div class="col-25">
                      <label for="tanggal_keluar">
                        Rujukan: {{form.rujukan}}
                      </label>
                    </div>
                  
                 


                  <div class="row">
                    <div class="col-25">
                      <label for="tanggal_keluar">
                        Alamat : 
                      </label>
                    </div>
                  </div>

                  <div class="row">
                    <div class="col-25">
                      <label for="tanggal_keluar">
                        Jalan
                      </label>
                    </div>
                    <div class="col-75">
                      {{ form.jalan }}
                    </div>
                  </div>

                  <div class="row">
                    <div class="col-25">
                      <label for="tanggal_keluar">
                        Kelurahan
                      </label>
                    </div>
                    <div class="col-75">
                      {{ form.kelurahan }}
                    </div>
                  </div>

                  <div class="row">
                    <div class="col-25">
                      <label for="tanggal_keluar">
                        Kecamatan
                      </label>
                    </div>
                    <div class="col-75">
                      {{ form.kecamatan }}
                    </div>
                  </div>

                  <div class="row">
                    <div class="col-25">
                      <label for="tanggal_keluar">
                        Kabupaten/Kota
                      </label>
                    </div>
                    <div class="col-75">
                      {{ form.kabkot}}
                    </div>
                  </div>

                  <div class="row">
                    <div class="col-25">
                      <label for="tanggal_keluar">
                        Provinsi
                      </label>
                    </div>
                    <div class="col-75">
                      {{ form.prov}}
                    </div>
                  </div>
         
                <div class="row">
                  <input type="submit" value="Simpan">
                </div>


                </form>
            </div>
        </div>
    </section>
  </section>



{% endblock %}

trigger_5/templates/trigger_5/buat-paket-makan.html
{% extends 'base-sistem.html' %}
{% load static %}

{% block meta %}
<link rel="stylesheet" href="{% static 'css/trigger_1.css' %}">
<link rel="stylesheet" href="{% static 'main/css/home.css' %}">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
{% endblock %}


{% block content %}

<script language="javascript" type="text/javascript">
  
  $(document).ready(function () {

    $("#kode_hotel").change(function () {
        var el = $(this);
        var data = JSON.parse("{{data|escapejs}}");  //ngambil data yang di transfer dari views supaya bisa dipake gi js

        var list = document.getElementById("kode_ruangan"); //clear data sebelumnya
        while (list.hasChildNodes()) {
          list.removeChild(list.firstChild);
        }

        const keys = Object.keys(data); // ngambil key-key yang ada dalam bentuk list
        for (i = 0; i < keys.length; i++) {
          if (el.val() == keys[i]) {   
            var temp = data[keys[i]]; //list dari kode room
            for (j = 0; j < temp.length ; j++) {  //masukin optionnya
              $("#kode_ruangan").append("<option>"+temp[j]+"</option>");
              
            }break;
          }
         
        }
        
       
    });

    });

    function Validation()
    {
      var entrydate, outdate;
      entrydate = document.getElementById("id_tanggal_masuk").value;
      outdate = document.getElementById("id_tanggal_keluar").value;
      if(entrydate > outdate)
      
      {
          event.preventDefault();
          alert("Maaf, tolong masukan tanggal keluar > tanggal masuk");
          returnToPreviousPage();
          return false;
      }
      return true;
    }
 
  </script>

<br><br><br><br>
<section class="home">
    <section class="section2">
        <div class="parent-card">
            <div class="box-card">
              <h2 class="title">BUAT PAKET MAKAN</h2><br>
                          
              <form method="POST" action="{% url 'trigger_5:buat_paket_makan' %}"  onsubmit="Validation();">
                {% csrf_token %}

                <label for="nik_pasien">Kode Hotel</label>
                  <select id="kode_hotel" name="kode_hotel">
                    {% for data in kode_hotel %}
                    <option>{{ data }}</option>
                    {% endfor %}
                  </select>

                  <div class="row">
                    <div class="col-25">
                      <label for="jenis_bed">
                        Kode Paket
                      </label>
                    </div>
                    <div class="col-75">
                      {{ form.kode_paket }}
                    </div>
                  </div>
                
                  <div class="row">
                    <div class="col-25">
                      <label for="tanggal_keluar">
                        Nama Paket
                      </label>
                    </div>
                    <div class="col-75">
                      {{ form.nama_paket }}
                    </div>
                  </div>

                  


                  <div class="row">
                    <div class="col-25">
                      <label for="tanggal_keluar">
                        Harga
                      </label>
                    </div>
                    <div class="col-75">
                      {{ form.harga }}
                    </div>
                  </div>
         
                <div class="row">
                  <input type="submit" value="Simpan">
                </div>


                </form>
            </div>
        </div>
    </section>
  </section>



{% endblock %}

trigger_5/templates/trigger_5/lihat-hotel-satgas.html
{% extends 'base-satgas.html' %}
{% load static %}

{% block meta %}
<link rel="stylesheet" href="{% static 'css/trigger_1.css' %}">
<link rel="stylesheet" href="{% static 'main/css/home.css' %}">

{% endblock %}

{% block content %}
<br><br><br><br>
<table style="width:100%" class="tablenomor">
    <tr>
      <th>No.</th>
      <th>Kode</th>
      <th>Hotel</th>
      <th>Rujukan</th>
      <th>Alamat</th>
    </tr>

    {% for row in table %}
    <tr>
      <td> </td>
      <td> {{ row.kode }} </td> 
      <td> {{ row.nama }} </td> 
      {% if row.isrujukan == '1' %} 
      <td><input type="checkbox" name="check" value="check" checked disabled></td>
      {% else %}
      <td><input type="checkbox" disabled></td>
      {% endif %}
      <td> {{ row.jalan }}, {{ row.kelurahan }}, {{ row.kecamatan }}, {{ row.kabkot }}, {{ row.prov }} </td>
    </tr>
    
    {% endfor %}

  </table>


{% endblock %}

trigger_5/templates/trigger_5/lihat-hotel-sistem.html
{% extends 'base-sistem.html' %}
{% load static %}

{% block meta %}
<link rel="stylesheet" href="{% static 'css/trigger_1.css' %}">
<link rel="stylesheet" href="{% static 'main/css/home.css' %}">

{% endblock %}

{% block content %}
<br><br><br><br>
<table style="width:100%" class="tablenomor">
    <tr>
      <th>No.</th>
      <th>Kode</th>
      <th>Hotel</th>
      <th>Rujukan</th>
      <th>Alamat</th>
      <th>Action</th>
    </tr>

    {% for row in table %}
    <tr>
      <td> </td>
      <td> {{ row.kode }} </td> 
      <td> {{ row.nama }} </td> 
      {% if row.isrujukan == '1' %} 
      <td><input type="checkbox" name="check" value="check" checked disabled></td>
      {% else %}
      <td><input type="checkbox" disabled></td>
      {% endif %}
      <td> {{ row.jalan }}, {{ row.kelurahan }}, {{ row.kecamatan }}, {{ row.kabkot }}, {{ row.prov }} </td>
      <td> <a class="tombol-update" href="{% url 'trigger_5:update_hotel' kode=row.kode %}">UPDATE</a> </td>
    </tr>
    
    {% endfor %}

  </table>


{% endblock %}

trigger_5/templates/trigger_5/lihat-hotel.html
{% extends 'base-pengguna-publik.html' %}
{% load static %}

{% block meta %}
<link rel="stylesheet" href="{% static 'css/trigger_1.css' %}">
<link rel="stylesheet" href="{% static 'main/css/home.css' %}">

{% endblock %}

{% block content %}
<br><br><br><br>
<table style="width:100%" class="tablenomor">
    <tr>
      <th>No.</th>
      <th>Kode</th>
      <th>Hotel</th>
      <th>Rujukan</th>
      <th>Alamat</th>
    </tr>

    {% for row in table %}
    <tr>
      <td> </td>
      <td> {{ row.kode }} </td> 
      <td> {{ row.nama }} </td> 
      {% if row.isrujukan == '1' %} 
      <td><input type="checkbox" name="check" value="check" checked disabled></td>
      {% else %}
      <td><input type="checkbox" disabled></td>
      {% endif %}
      <td> {{ row.jalan }}, {{ row.kelurahan }}, {{ row.kecamatan }}, {{ row.kabkot }}, {{ row.prov }} </td>
    </tr>
    
    {% endfor %}

  </table>


{% endblock %}

trigger_5/templates/trigger_5/lihat-paket-makan-sistem.html
{% extends 'base-sistem.html' %}
{% load static %}

{% block meta %}
<link rel="stylesheet" href="{% static 'css/trigger_1.css' %}">
<link rel="stylesheet" href="{% static 'main/css/home.css' %}">

{% endblock %}

{% block content %}
<br><br><br><br>
<table style="width:100%" class="tablenomor">
    <tr>
      <th>No.</th>
      <th>Hotel</th>
      <th>Kode Paket</th>
      <th>Nama Paket</th>
      <th>Harga</th>
      <th>Action</th>
    </tr>

    {% for row in table %}
    <tr>
      <td> </td>
      <td> {{ row.kodehotel }} </td> 
      <td> {{ row.kodepaket }} </td> 
      <td> {{ row.nama }} </td> 
      <td> {{ row.harga }} </td> 
      <td> <a class="tombol-update" href="{% url 'trigger_5:update_paket_makan' kodehotel=row.kodehotel kodepaket=row.kodepaket  %}">UPDATE</a></td>
      <td> <a class="tombol-delete" href="{% url 'trigger_5:delete_paket_makan' kodehotel=row.kodehotel kodepaket=row.kodepaket  %}">DELETE</a> </td>
      
    </tr>
    
    {% endfor %}

  </table>


{% endblock %}

trigger_5/templates/trigger_5/lihat-transaksi-makan-satgas.html
{% extends 'base-satgas.html' %}
{% load static %}

{% block meta %}
<link rel="stylesheet" href="{% static 'css/trigger_1.css' %}">
<link rel="stylesheet" href="{% static 'main/css/home.css' %}">

{% endblock %}

{% block content %}
<br><br><br><br>
<table style="width:100%" class="tablenomor">
    <tr>
      <th>No.</th>
      <th>Id Transaksi Hotel</th>
      <th>Id Transaksi</th>
      <th>Total Bayar</th>
      <th>Action</th>
    </tr>

    {% for row in table %}
    <tr>
      <td> </td>
      <td> {{ row.idtransaksi }} </td> 
      <td> {{ row.idtransaksimakan }} </td> 
      <td> {{ row.totalbayar }} </td>
      <td> <a class="tombol-detail" href="{% url 'trigger_5:lihat_transaksi_makan_detail' idtransaksi=row.idtransaksi idtransaksimakan=row.idtransaksimakan %}">DETAIL</a> </td>
      {% if row.statusbayar != "LUNAS" %} 
      <td> <a class="tombol-update" href="#">UPDATE</a> </td>
      <td> <a class="tombol-delete" href="{% url 'trigger_5:delete_transaksi_makan' idtransaksi=row.idtransaksi idtransaksimakan=row.idtransaksimakan %}">DELETE</a> </td> 
      {% endif %} 
      
    </tr>
    
    {% endfor %}

  </table>


{% endblock %}

trigger_5/templates/trigger_5/lihat-transaksi-makan.html
{% extends 'base-pengguna-publik.html' %}
{% load static %}

{% block meta %}
<link rel="stylesheet" href="{% static 'css/trigger_1.css' %}">
<link rel="stylesheet" href="{% static 'main/css/home.css' %}">

{% endblock %}

{% block content %}
<br><br><br><br>
<table style="width:100%" class="tablenomor">
    <tr>
      <th>No.</th>
      <th>Id Transaksi Hotel</th>
      <th>Id Transaksi</th>
      <th>Total Bayar</th>
      <th>Action</th>
    </tr>

    {% for row in table %}
    <tr>
      <td> </td>
      <td> {{ row.idtransaksi }} </td> 
      <td> {{ row.idtransaksimakan }} </td> 
      <td> {{ row.totalbayar }} </td> 
      <td> <a class="tombol-detail" href="{% url 'trigger_5:lihat_transaksi_makan_detail' idtransaksi=row.idtransaksi idtransaksimakan=row.idtransaksimakan %}">DETAIL</a> </td>
    </tr>
    
    {% endfor %}

  </table>


{% endblock %}