main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

project_name/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('trigger-1/', include('trigger_1.urls')),
    path('trigger-2/', include('trigger_2.urls')),
    path('trigger-3/', include('trigger_3.urls')),
    path('trigger-4/', include('trigger_4.urls')),
    path('trigger-5/', include('trigger_5.urls'))
]

trigger_2/urls.py
from django.urls import path

from . import views

app_name = 'trigger_2'

urlpatterns = [
    path('lihat-jadwal-dokter/', views.lihat_jadwal_dokter, name='lihat_jadwal_dokter'),
    path('list-buat-jadwal-dokter/', views.list_buat_jadwal_dokter, name='list_buat_jadwal_dokter'),
    path('buat-jadwal/<str:kode_faskes>/<str:shift>/<str:tanggal>', views.buat_jadwal_dokter, name='buat_jadwal_dokter'),

    path('list-create-appointment/', views.list_create_appointment, name='list_create_appointment'),
    path('create-appointment/<str:nostr>/<str:username>/<str:kode_faskes>/<str:tgl_praktek>/<str:shift_praktek>', views.create_appointment, name='create_appointment'),
    path('read-appointment/', views.read_appointment, name='read_appointment'),
    path('delete-appointment/<str:nik>/<str:email_dokter>/<str:shift_praktek>/<str:tgl_praktek>/<str:kode_faskes>', views.delete_appointment, name='delete_appointment'),
    path('update-appointment/<str:nik>/<str:email_dokter>/<str:shift_praktek>/<str:tgl_praktek>/<str:kode_faskes>', views.update_appointment, name='update_appointment'),

    path('create-ruangan-rs/', views.create_ruangan_rs, name='create_ruangan_rs'),
    path('list-ruangan-rs/', views.list_ruangan_rs, name='list_ruangan_rs'),
    path('update-ruangan-rs/<str:koders>/<str:koderuangan>/<str:tipe>/<int:harga>', views.update_ruangan_rs, name='update_ruangan_rs'),
    path('create-bed-rs/', views.create_bed_rs, name='create_bed_rs'),
    path('list-bed-rs/', views.list_bed_rs, name='list_bed_rs'),
    path('delete-bed-rs/<str:koderuangan>/<str:koders>/<str:kodebed>', views.delete_bed_rs, name='delete_bed_rs'),
]

trigger_2/models.py
from django.db import models

# Create your models here.

trigger_2/forms.py
from django import forms

class UpdateRekomendasi(forms.Form):
    rekomendasi = forms.CharField(max_length=500,widget=forms.Textarea, required=False) 

class CreateRuanganRS(forms.Form):
    tipe = forms.CharField(max_length=10, required=False)
    harga = forms.IntegerField(required=False)
    kode_ruangan = forms.CharField(max_length=5, required=False)

class UpdateRuanganRS(forms.Form):
    tipe = forms.CharField(max_length=10, required=False) 
    harga = forms.IntegerField(required=True) 

trigger_2/views.py
from django.shortcuts import render, reverse, redirect
from .forms import *
from django.db import connection
from collections import namedtuple
from django.http import HttpResponseRedirect, JsonResponse
from django.db import IntegrityError, InternalError
from json import dumps
import datetime

def namedtuplefetchall(cursor):
    "Return all rows from a cursor as a namedtuple"
    desc = cursor.description
    nt_result = namedtuple('Result', [col[0] for col in desc])
    return [nt_result(*row) for row in cursor.fetchall()]

# Fitur nomor 4

def check_peran(email):
    cursor = connection.cursor()
    cursor.execute("set search_path to siruco")
    cursor.execute("select * from akun_pengguna where username='"+email+"'")
    hasil = namedtuplefetchall(cursor)
    peran = hasil[0].peran
    cursor.execute("set search_path to public")
    cursor.close()
    return peran

def check_base(email):
    peran = check_peran(email)
    base_html = ''
    if(peran == 'Pengguna_publik'):
        return 'base-pengguna-publik.html'
    elif(peran == 'Admin_satgas'):
        return 'base-satgas.html'

def lihat_jadwal_dokter(request):
    username = request.session['email']
    peran = check_peran(username)
    cursor = connection.cursor()
    cursor.execute("set search_path to siruco")
    if(peran == 'Dokter'):
        cursor.execute("select * from jadwal_dokter where username = '" + username +"'")
        hasil = namedtuplefetchall(cursor)
        cursor.execute("set search_path to public")
        argument = {
            'table':hasil,
        }
        cursor.close()
        return render(request, 'trigger_2/lihat-jadwal-viewonly-dokter.html', argument)

    elif(peran == 'Admin_satgas'):
        cursor.execute("select * from jadwal_dokter")
        hasil = namedtuplefetchall(cursor)
        argument = {
            'table':hasil,
        }
        cursor.close()
        return render(request, 'trigger_2/lihat-jadwal-viewonly-satgas.html', argument)

    elif(peran == 'Pengguna_publik'):
        cursor.execute("select * from jadwal_dokter")
        hasil = namedtuplefetchall(cursor)
        argument = {
            'table':hasil,
        }
        cursor.close()
        return render(request, 'trigger_2/lihat-jadwal-viewonly-pengguna.html', argument)

def list_buat_jadwal_dokter(request):
    dokter = request.session['email']
    cursor = connection.cursor()
    cursor.execute("set search_path to siruco")
    cursor.execute("(select * from jadwal) except (select kode_faskes, shift, tanggal from jadwal_dokter where username = '" + dokter +"')")
    hasil = namedtuplefetchall(cursor)
    cursor.execute("set search_path to public")
    argument = {
        'table':hasil,
    }
    cursor.close()
    return render(request, 'trigger_2/buat-jadwal.html', argument)

def buat_jadwal_dokter(request, kode_faskes, shift, tanggal):
    dokter = request.session['email']
    cursor = connection.cursor()
    cursor.execute("set search_path to siruco")
    cursor.execute("select * from dokter where username ='"+dokter+ "'")
    data_dokter = namedtuplefetchall(cursor)
    nostr = data_dokter[0].nostr
    
    cursor.execute("insert into jadwal_dokter values('"+ nostr +"','"+ dokter +"','"+ kode_faskes +"','"+ shift +"','"+ tanggal + "', 0)")
    cursor.execute("set search_path to public")
    cursor.close()
    return redirect('trigger_2:lihat_jadwal_dokter')

# Fitur nomor 5

def list_create_appointment(request, pesan=''):
    username = request.session['email']
    base_html = check_base(username)
    cursor = connection.cursor()
    cursor.execute("set search_path to siruco")
    cursor.execute("select * from jadwal_dokter")
    jadwal_dokter = namedtuplefetchall(cursor)

    argument = {
        'base_html': base_html,
        'jadwal_dokter': jadwal_dokter,
        'pesan': pesan,
    }
 
    cursor.execute("set search_path to public")
    cursor.close()
    return render(request, 'trigger_2/list-create-appointment.html', argument)

def create_appointment(request, nostr, username, kode_faskes, tgl_praktek, shift_praktek):
    if request.method == "POST":
        nik = str(request.POST['nik_pasien'])
        cursor = connection.cursor()
        cursor.execute("set search_path to siruco")
        try:
            cursor.execute("insert into memeriksa values('"+ nik +"','"+ nostr +"','"+ username + "','" + kode_faskes +"','"+ shift_praktek +"','"+ tgl_praktek + "')")
            cursor.execute("set search_path to public")
            cursor.close()
            return redirect('trigger_2:list_create_appointment') # NANTI DIGANTI REDIRECT KE LIST APPOINTMENT
        except InternalError:
            print("masuk sini ga")
            pesan = 'Silahkan pilih shift dan tanggal lainnya, karena shift dan tanggal yang dipilih sudah penuh'
            cursor.execute("set search_path to public")
            cursor.close()
            return list_create_appointment(request, pesan)

    email = request.session['email']
    base_html = check_base(email)
    list_nik = []
    peran = check_peran(email)
    cursor = connection.cursor()
    cursor.execute("set search_path to siruco")
    
    # disini saya tambahin constraint, kalau kombinasi: nik, nostr, username, kode_faskes, tgl_praktek, shift_praktek sudah ada di memeriksa 
    # maka tidak akan ditampilkan pada dropdown nik.
    # karena kalau tidak ditambahkan constraint ini, jika pasien tsb sudah dibuatkan appointment sesuai appointment yang dipilih maka akan error.

    if(peran == 'Pengguna_publik'):
        cursor.execute("select * from pasien where idpendaftar='"+email+"' AND nik not in (select nik_pasien from memeriksa where nostr='"+ nostr +"' AND username_dokter='"+ username+"' AND kode_faskes = '"+ kode_faskes +"' AND praktek_shift = '"+ shift_praktek +"' AND praktek_tgl='"+ tgl_praktek +"')") 
        hasil = namedtuplefetchall(cursor)
        for x in range (len(hasil)):
            list_nik.append(hasil[x].nik)

    elif(peran == 'Admin_satgas'):
        cursor.execute("select * from pasien where nik not in (select nik_pasien from memeriksa where nostr='"+ nostr +"' AND username_dokter='"+ username+"' AND kode_faskes = '"+ kode_faskes +"' AND praktek_shift = '"+ shift_praktek +"' AND praktek_tgl='"+ tgl_praktek +"')") 
        hasil = namedtuplefetchall(cursor)
        for x in range (len(hasil)):
            list_nik.append(hasil[x].nik)

    argument = {
        'base_html': base_html,
        'list_nik': list_nik,
        'username': username,
        'kode_faskes': kode_faskes,
        'tgl_praktek': tgl_praktek,
        'shift_praktek': shift_praktek,
    }
    cursor.execute("set search_path to public")
    cursor.close()
    return render(request, 'trigger_2/create-appointment.html', argument)

def read_appointment(request, pesan=''):
    email = request.session['email']
    peran = check_peran(email)
    cursor = connection.cursor()
    cursor.execute("set search_path to siruco")
    if(peran == 'Pengguna_publik'):
        cursor.execute("select * from memeriksa where nik_pasien in (select nik from pasien where idpendaftar ='"+ email +"')")
        memeriksa = namedtuplefetchall(cursor)
        argument = {
            'memeriksa':memeriksa,
        }
        cursor.execute("set search_path to public")
        cursor.close()
        return render(request, 'trigger_2/read-appointment-viewonly-pengguna.html', argument)

    elif(peran == 'Admin_satgas'):
        cursor.execute("select * from memeriksa")
        memeriksa = namedtuplefetchall(cursor)
        argument = {
            'memeriksa':memeriksa,
        }
        cursor.execute("set search_path to public")
        cursor.close()
        return render(request, 'trigger_2/read-appointment-viewonly-satgas.html', argument)

    elif(peran == 'Dokter'):
        cursor.execute("select * from memeriksa where username_dokter='"+ email +"'")
        memeriksa = namedtuplefetchall(cursor)
        argument = {
            'memeriksa':memeriksa,
            'pesan':pesan,
        }
        cursor.execute("set search_path to public")
        cursor.close()
        return render(request, 'trigger_2/read-appointment-viewonly-dokter.html', argument)

def delete_appointment(request, nik, email_dokter, shift_praktek, tgl_praktek, kode_faskes):
    cursor = connection.cursor()
    cursor.execute("set search_path to siruco")
    cursor.execute("delete from memeriksa where nik_pasien='"+ nik +"' AND username_dokter='"+ email_dokter +"' AND kode_faskes='"+ kode_faskes +"' AND praktek_shift='"+ shift_praktek +"' AND praktek_tgl='"+ tgl_praktek +"'")
    # Tambahan: sehabis men-delete, jmlpasien pada jadwal_dokter juga disesuaikan
    cursor.execute("update jadwal_dokter set jmlpasien = jmlpasien-1 where username='"+ email_dokter +"' AND kode_faskes='"+ kode_faskes +"' AND shift='"+ shift_praktek +"' AND tanggal='"+ tgl_praktek +"'")
    cursor.execute("set search_path to public")
    cursor.close()
    return redirect('trigger_2:read_appointment')

def update_appointment(request, nik, email_dokter, shift_praktek, tgl_praktek, kode_faskes):
    cursor = connection.cursor()
    cursor.execute("set search_path to siruco")

    if request.method == "POST":
        rekomendasi=str(request.POST['rekomendasi'])
        if(rekomendasi!=''):
            cursor.execute("update memeriksa set rekomendasi='" + rekomendasi + "' where nik_pasien='"+ nik +"' AND username_dokter='"+ email_dokter +"' AND kode_faskes='"+ kode_faskes +"' AND praktek_shift='"+ shift_praktek +"' AND praktek_tgl='"+ tgl_praktek +"'")
            cursor.execute("set search_path to public")
            cursor.close()
            return redirect('trigger_2:read_appointment')
        else:
            pesan = 'Data yang diisikan belum lengkap, silahkan lengkapi data terlebih dahulu'
            cursor.execute("set search_path to public")
            cursor.close()
            return read_appointment(request, pesan)

trigger_2/templates/trigger_2/buat-jadwal.html
{% extends 'base-dokter.html' %}
{% load static %}

{% block meta %}
<link rel="stylesheet" href="{% static 'css/trigger_1.css' %}">
<link rel="stylesheet" href="{% static 'main/css/home.css' %}">

{% endblock %}

{% block content %}
<br><br><br><br>
<table style="width:100%">
    <tr>
      <th>Kode Faskes</th>
      <th>Shift</th>
      <th>Tanggal</th>
      <th>Buat Jadwal Dokter</th>
    </tr>
    {% for row in table %}
    <tr>
      <td> {{row.kode_faskes}} </td>
      <td> {{row.shift }} </td>
      <td> {{row.tanggal }} </td>
      <td> <a class="tombol-update" href="{% url 'trigger_2:buat_jadwal_dokter' kode_faskes=row.kode_faskes shift=row.shift tanggal=row.tanggal %}">CREATE</a></td>
    </tr>
    
{% endfor %}
  </table>


{% endblock %}

trigger_2/templates/trigger_2/create-appointment.html
{% extends base_html %}

{% load static %}

{% block meta %}
<link rel="stylesheet" href="{% static 'css/trigger_1.css' %}">
<link rel="stylesheet" href="{% static 'main/css/home.css' %}">

{% endblock %}

{% block content %}

<br><br><br>
<section class="home">
 
    <section class="section2">
        <div class="parent-card">
            <div class="box-card">
              <h2 class="title">FORM BUAT APPOINTMENT</h2>
              <form method="POST" action="">
                {% csrf_token %}

                <div class="row">
                  <label for="nik_pasien">NIK Pasien</label>
                  <select id="nik_pasien" name="nik_pasien">
                    {% for nik in list_nik %}
                    <option>{{ nik }}</option>
                    {% endfor %}
                  </select>
                </div>

                <div class="row">
                  <div class="col-25">
                    <label for="email">
                      Email Dokter
                    </label>
                  </div>
                  <div class="col-75">
                    <input value="{{ username }}" disabled></input>
                  </div>
                </div>

                <div class="row">
                  <div class="col-25">
                    <label for="email">
                      Kode Faskes
                    </label>
                  </div>
                  <div class="col-75">
                    <input value="{{ kode_faskes }}" disabled></input>
                  </div>
                </div>

                <div class="row">
                  <div class="col-25">
                    <label for="email">
                      Tanggal Praktek
                    </label>
                  </div>
                  <div class="col-75">
                    <input value="{{ tgl_praktek }}" disabled></input>
                    
                  </div>
                </div>

                <div class="row">
                  <div class="col-25">
                    <label for="email">
                      Shift Praktek
                    </label>
                  </div>
                  <div class="col-75">
                    <input value="{{ shift_praktek }}" disabled></input>
                    
                  </div>
                </div>

                <div class="row">
                  <input type="submit" value="SIMPAN">
                </div>
                </form>
            </div>
     
        </div>
    </section>
  </section>


{% endblock %}

trigger_2/templates/trigger_2/create-bed-rs.html
{% extends 'base-satgas.html' %}

{% load static %}

{% block meta %}
<link rel="stylesheet" href="{% static 'css/trigger_1.css' %}">
<link rel="stylesheet" href="{% static 'main/css/home.css' %}">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

{% endblock %}

{% block content %}

<script language="javascript" type="text/javascript">
    $(document).ready(function () {
        $("#kode_rs").change(function () {
            var kode_rs_selected = $(this);
            var data = JSON.parse("{{data|escapejs}}");

            var list = document.getElementById("kode_room"); //clear data sebelumnya
            while (list.hasChildNodes()) {
            list.removeChild(list.firstChild);
            }
            
            const keys = Object.keys(data);
            
            for (i = 0; i < keys.length; i++) {
                if(kode_rs_selected.val() == keys[i]) {
                    var temp = data[keys[i]];
                    for(j = 0; j < temp.length; j ++) {
                        $("#kode_room").append("<option>"+ temp[j] +"</option>")
                    } break;
                } 
            }
        });

    });

</script>

<br><br><br>

<section class="home">
    <section class="section2">
        <h3 style="color: red;">{{ pesan }}</h3>
        <div class="parent-card">
            <div class="box-card">
              <h2 class="title">FORM BUAT BED RS</h2>
              <form action="" method="POST">
                {% csrf_token %}

                <div class="row">
                  <label>Kode Rumah Sakit</label>
                  <select id="kode_rs" name="kode_rs">
                    {% for kode in list_kode_rs %}
                    <option>{{ kode }}</option>
                    {% endfor %}
                  </select>
                </div>

                <div class="row">
                    <label>Kode Ruangan</label>
                    <select id="kode_room" name="kode_room">
                    </select>
                </div>

                <div class="row">
                  <div class="col-25">
                    <label for="kode_bed">
                      Kode Bed
                    </label>
                  </div>
                  <div class="col-75">
                    <input for='kode_bed' id ='kode_bed' value="Bxx" disabled></input>
                  </div>
                </div>

                <div class="row" id="submit">
                  <input type="submit" value="SIMPAN">
                </div>
                </form>
            </div>
     
        </div>
    </section>
  </section>



{% endblock %}

trigger_2/templates/trigger_2/create-ruangan-rs.html
{% extends 'base-satgas.html' %}

{% load static %}

{% block meta %}
<link rel="stylesheet" href="{% static 'css/trigger_1.css' %}">
<link rel="stylesheet" href="{% static 'main/css/home.css' %}">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

{% endblock %}

{% block content %}

<script language="javascript" type="text/javascript">
    $(document).ready(function () {
        var temp = '';
        $("#kode_rs").change(function () {
            var list = document.getElementById("kode_room"); //clear data sebelumnya

            while (list.hasChildNodes()) {
            list.removeChild(list.firstChild);
            }

            var kode_rs_selected = $(this);
            var data = JSON.parse("{{data|escapejs}}");
            console.log(kode_rs_selected)
            const keys = Object.keys(data);
            
            for (i = 0; i < keys.length; i++) {
                if (kode_rs_selected.val() == keys[i]) {  
                    var temp = data[keys[i]];
                } 
            } 
            $("#kode_room").append("<input for='kode_ruangan' id ='kode_ruangan' value="+ temp +" disabled></input>");
        });

    });

</script>

<br><br><br>

<section class="home">
    <section class="section2">
        <h3 style="color: red;">{{ pesan }}</h3>
        <div class="parent-card">
            <div class="box-card">
              <h2 class="title">FORM BUAT RUANGAN RS</h2>
              <form action="" method="POST">
                {% csrf_token %}

                <div class="row">
                  <label>Kode Rumah Sakit</label>
                  <select id="kode_rs" name="kode_rs">
                    {% for kode in list_kode_rs %}
                    <option>{{ kode }}</option>
                    {% endfor %}
                  </select>
                </div>

                <div class="row">
                  <div class="col-25">
                    <label>
                        Kode Ruangan
                    </label>
                  </div>
                  <div class="col-75" id='kode_room'>
                    
                  </div>
                </div>

                <div class="row">
                  <div class="col-25">
                    <label for="tipe">
                      Tipe
                    </label>
                  </div>
                  <div class="col-75">
                    {{ formulir.tipe }}
                  </div>
                </div>

                <div class="row">
                  <div class="col-25">
                    <label for="harga_ruangan">
                      Harga Ruangan
                    </label>
                  </div>
                  <div class="col-75">
                    {{ formulir.harga }}
                  </div>
                </div>

                <div class="row" id="submit">
                  <input type="submit" value="SIMPAN">
                </div>
                </form>
            </div>
     
        </div>
    </section>
  </section>



{% endblock %}

trigger_2/templates/trigger_2/list-bed-rs.html
{% extends 'base-satgas.html' %}

{% load static %}

{% block meta %}
<link rel="stylesheet" href="{% static 'css/trigger_1.css' %}">
<link rel="stylesheet" href="{% static 'main/css/home.css' %}">

{% endblock %}

{% block content %}
<br><br><br><br>

<table style="width:100%">
    <tr>
      <th>Kode RS</th>
      <th>Kode Ruangan</th>
      <th>Kode Bed</th>
      <th>Action</th>
    </tr>

    {% for row in bed_rs %}
    <tr>
      <td> {{ row.koders }} </td>
      <td> {{ row.koderuangan }} </td> 
      <td> {{ row.kodebed }} </td>
      {% if row.kodebed not in bed_rs_reserved %}
      <td> <a class="tombol-delete" href="{% url 'trigger_2:delete_bed_rs' koderuangan=row.koderuangan koders=row.koders kodebed=row.kodebed %}">Delete</a></td>
      {% else %}
        {% for key, value in dict_tglkeluar.items %}
        {% if key == row.kodebed and date > value %}
        <td> <a class="tombol-delete" href="{% url 'trigger_2:delete_bed_rs' koderuangan=row.koderuangan koders=row.koders kodebed=row.kodebed %}">Delete</a></td>
        {% endif %}
      
        {% endfor %}
    {% endif %}
    </tr>
    {% endfor %}
  </table>


{% endblock %}

trigger_2/templates/trigger_2/list-create-appointment.html
{% extends base_html %}

{% load static %}

{% block meta %}
<link rel="stylesheet" href="{% static 'css/trigger_1.css' %}">
<link rel="stylesheet" href="{% static 'main/css/home.css' %}">

{% endblock %}

{% block content %}
<br><br><br><br>
<section class="center-tittle">
  <h3 style="color: red;">{{ pesan }}</h3>
</section>

<table style="width:100%">
    <tr>
      <th>No STR</th>
      <th>Email Dokter</th>
      <th>Faskes</th>
      <th>Shift</th>
      <th>Tanggal</th>
      <th>Buat Appointment</th>
    </tr>

    {% for row in jadwal_dokter %}
    <tr>
      <td> {{ row.nostr }} </td>
      <td> {{ row.username }} </td>
      <td> {{ row.kode_faskes }} </td> 
      <td> {{ row.shift }} </td> 
      <td> {{ row.tanggal }} </td> 
      <td> <a class="tombol-update" href="{% url 'trigger_2:create_appointment' nostr=row.nostr username=row.username kode_faskes=row.kode_faskes tgl_praktek=row.tanggal shift_praktek=row.shift %}">Book</a></td> 
    </tr>
    
    {% endfor %}

  </table>


{% endblock %}

trigger_2/templates/trigger_2/list-ruangan-rs.html
{% extends 'base-satgas.html' %}

{% load static %}

{% block meta %}
<link rel="stylesheet" href="{% static 'css/trigger_1.css' %}">
<link rel="stylesheet" href="{% static 'main/css/home.css' %}">

{% endblock %}

{% block content %}
<br><br><br><br>

<table style="width:100%">
    <tr>
      <th>Kode RS</th>
      <th>Kode Ruangan</th>
      <th>Tipe</th>
      <th>Jumlah Bed</th>
      <th>Harga Ruangan</th>
      <th>Action</th>
    </tr>

    {% for row in ruangan_rs %}
    <tr>
      <td> {{ row.koders }} </td>
      <td> {{ row.koderuangan }} </td> 
      <td> {{ row.tipe }} </td> 
      <td> {{ row.jmlbed }} </td> 
      <td> {{ row.harga }} </td> 
      <td> <a class="tombol-update" href="{% url 'trigger_2:update_ruangan_rs' koders=row.koders koderuangan=row.koderuangan tipe=row.tipe harga=row.harga %}">Update</a></td> 
    </tr>
    
    {% endfor %}

  </table>


{% endblock %}

trigger_2/templates/trigger_2/read-appointment-viewonly-dokter.html
{% extends 'base-dokter.html' %}

{% load static %}

{% block meta %}
<link rel="stylesheet" href="{% static 'css/trigger_1.css' %}">
<link rel="stylesheet" href="{% static 'main/css/home.css' %}">

{% endblock %}

{% block content %}
<br><br><br><br>
<section class="center-tittle">
  <h3 style="color: red;">{{ pesan }}</h3>
</section>
<table style="width:100%">
    <tr>
      <th>NIK Pasien</th>
      <th>Email Dokter</th>
      <th>Faskes</th>
      <th>Shift</th>
      <th>Tanggal</th>
      <th>Rekomendasi</th>
      <th>Action</th>
    </tr>

    {% for row in memeriksa %}
    <tr>
      <td> {{ row.nik_pasien }} </td>
      <td> {{ row.username_dokter }} </td> 
      <td> {{ row.kode_faskes }} </td> 
      <td> {{ row.praktek_shift }} </td> 
      <td> {{ row.praktek_tgl }} </td>
      <td> {{ row.rekomendasi }} </td>
      <td> <a class="tombol-update" href="{% url 'trigger_2:update_appointment' nik=row.nik_pasien email_dokter=row.username_dokter shift_praktek=row.praktek_shift tgl_praktek=row.praktek_tgl kode_faskes=row.kode_faskes %}">Update</a></td>  
    </tr>
    
    {% endfor %}

  </table>


{% endblock %}

trigger_2/templates/trigger_2/read-appointment-viewonly-satgas.html
{% extends 'base-satgas.html' %}

{% load static %}

{% block meta %}
<link rel="stylesheet" href="{% static 'css/trigger_1.css' %}">
<link rel="stylesheet" href="{% static 'main/css/home.css' %}">

{% endblock %}

{% block content %}
<br><br><br><br>

<table style="width:100%">
    <tr>
      <th>NIK Pasien</th>
      <th>Email Dokter</th>
      <th>Faskes</th>
      <th>Shift</th>
      <th>Tanggal</th>
      <th>Rekomendasi</th>
      <th>Action</th>
    </tr>

    {% for row in memeriksa %}
    <tr>
      <td> {{ row.nik_pasien }} </td>
      <td> {{ row.username_dokter }} </td> 
      <td> {{ row.kode_faskes }} </td> 
      <td> {{ row.praktek_shift }} </td> 
      <td> {{ row.praktek_tgl }} </td>
      <td> {{ row.rekomendasi }} </td>
      <td> <a class="tombol-delete" href="{% url 'trigger_2:delete_appointment' nik=row.nik_pasien email_dokter=row.username_dokter shift_praktek=row.praktek_shift tgl_praktek=row.praktek_tgl kode_faskes=row.kode_faskes %}">Delete</a></td>  
    </tr>
    
    {% endfor %}

  </table>


{% endblock %}