main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

project_name/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('trigger-1/', include('trigger_1.urls')),
    path('trigger-2/', include('trigger_2.urls')),
    path('trigger-3/', include('trigger_3.urls')),
    path('trigger-4/', include('trigger_4.urls')),
    path('trigger-5/', include('trigger_5.urls'))
]

trigger_3/urls.py
from django.urls import path

from . import views

app_name = 'trigger_3'

urlpatterns = [
    path('buat-reservasi-rs/', views.create_reservasi_rs, name='buat_reservasi_rs'),
    path('list-reservasi-rs/', views.list_reservasi_rs, name='list_reservasi_rs'),
    path('delete-reservasi-rs/<str:kodepasien>/<str:tglmasuk>', views.delete_reservasi, name='delete-reservasi-rs'),
    path('update-reservasi-rs/<str:kodepasien>/<str:tglmasuk>', views.update_reservasi, name='update-reservasi-rs'),
    path('buat-faskes/', views.buat_faskes, name='buat-faskes'),
    path('list-faskes/', views.list_faskes, name='list-faskes'),
    path('delete-faskes/<str:kodefaskes>', views.delete_faskes, name='delete-faskes'),
    path('update-faskes/<str:kodefaskes>', views.update_faskes, name='update-faskes'),
    path('detail-faskes/<str:kodefaskes>', views.detail_faskes, name='detail-faskes'),
    path('buat-jadwal-faskes/', views.buat_jadwal_faskes, name='buat-jadwal-faskes'),
    path('list-jadwal-faskes/', views.list_jadwal_faskes, name='list-jadwal-faskes'),
    path('buat-rumah-sakit/', views.buat_rumah_sakit, name='buat-rumah-sakit'),
    path('list-rumah-sakit/', views.list_rumah_sakit, name='list-rumah-sakit'),
    path('update-rs/<str:kodefaskes>', views.update_rs, name='update-rs'),
    path('list-transaksi-rs/', views.list_transaksi_rs, name='list-transaksi-rs'),
    path('delete-transaksi-rs/<str:id>', views.delete_transaksi_rs, name='delete-transaksi-rs'),
    path('update-transaksi-rs/<str:id>', views.update_transaksi_rs, name='update-transaksi-rs'),

]

trigger_3/models.py
from django.db import models

# Create your models here.

trigger_3/forms.py
from django import forms
from django.db import connection
import datetime

cursor = connection.cursor()
cursor.execute("SELECT nik FROM SIRUCO.PASIEN")
select = cursor.fetchall()

nik_pasien = [tuple([select[x][0], select[x][0]]) for x in range(len(select))]
select=''

cursor.execute("SELECT kode_faskes FROM SIRUCO.RUMAH_SAKIT")
select = cursor.fetchall()
kode_rumah_sakit = [tuple([select[x][0], select[x][0]]) for x in range(len(select))]

# cursor.execute("SELECT kode_faskes FROM SIRUCO.RUMAH_SAKIT")
# select = cursor.fetchall()
# kode_ruangan = [tuple([select[x][0], select[x][0]]) for x in range(len(select))]


cursor.execute("SELECT kode FROM SIRUCO.FASKES")
select = cursor.fetchall()
kode_faskes = [tuple([select[x][0], select[x][0]]) for x in range(len(select))]
print("=======")
print(select)



class FormReservasiRS(forms.Form):
    tanggal_masuk = forms.DateField(initial=datetime.date.today)
    tanggal_keluar = forms.DateField(initial=datetime.date.today() + datetime.timedelta(days=3))
    kode_rs = forms.CharField(widget=forms.Select(choices=kode_rumah_sakit, attrs={
        'class': 'form-control',
        'placeholder' : 'Kode Rumah Sakit',
        'required': True,
    }))

    # kode_ruangan = forms.CharField(widget=forms.Select(choices=kode_rumah_sakit, attrs={
    #     'class': 'form-control',
    #     'placeholder' : 'Kode Ruangan',
    #     'required': True,
    # }))

    kode_bed = forms.CharField(max_length=5, required=True) 

class FormUpdateReservasiRS(forms.Form):
    tanggal_keluar = forms.DateField()

class FormFaskes(forms.Form):
    tipe = forms.CharField(widget=forms.Select(choices=[('RUJ', 'RUJ'), ('IDD', 'IDD'), ('KLI', 'KLI'), ('PUS', 'PUS')], attrs={
        'class': 'form-control',
        'placeholder' : 'Tipe',
        'required': True,
    }))

    nama_faskes = forms.CharField(max_length=50, required=True) 

    status_kepemilikan = forms.CharField(widget=forms.Select(choices=[('Pemerintah', 'Pemerintah'), ('Swasta', 'Swasta')], attrs={
        'class': 'form-control',
        'placeholder' : 'Status',
        'required': True,
    }))

    jalan = forms.CharField(max_length=30, required=True)
    kelurahan = forms.CharField(max_length=30, required=True)
    kecamatan = forms.CharField(max_length=30, required=True)
    kabupaten_kota = forms.CharField(max_length=30, required=True)
    provinsi = forms.CharField(max_length=30, required=True)

class FormJadwalFaskes(forms.Form):
    # faskes = forms.CharField(widget=forms.Select(choices=kode_faskes, attrs={
    #     'class': 'form-control',
    #     'placeholder' : 'Tipe',
    #     'required': True,
    # }))
    shift = forms.CharField(max_length=15, required=True)
    tanggal = forms.DateField()

class FormRumahSakit(forms.Form):
    # faskes = forms.CharField(widget=forms.Select(choices=kode_faskes, attrs={
    #     'class': 'form-control',
    #     'placeholder' : 'Tipe',
    #     'required': True,
    # }))
    rujukan = forms.BooleanField(required=False)

class FormUpdateTransaksiRS(forms.Form):
    statusbayar = forms.CharField(max_length=15, required=True)


    

    

trigger_3/views.py
from django.shortcuts import render, reverse, redirect
from .forms import *
from django.db import connection
from collections import namedtuple
from django.http import HttpResponseRedirect
from django.db import IntegrityError, InternalError
from collections import namedtuple
from json import dumps
import datetime
from .forms import *

# Create your views here.

def namedtuplefetchall(cursor):
    "Return all rows from a cursor as a namedtuple"
    desc = cursor.description
    nt_result = namedtuple('Result', [col[0] for col in desc])
    return [nt_result(*row) for row in cursor.fetchall()]

def dictfetchall(cursor):
    "Return all rows from a cursor as a dict"
    columns = [col[0] for col in cursor.description]
    return [
        dict(zip(columns, row))
        for row in cursor.fetchall()
    ]


def create_reservasi_rs(request):
    # karena yang bisa akses url ini pada navbar hanya admin satgas jadi gak perlu bedain peran
    if request.method == "POST":
        formulir = FormReservasiRS(request.POST)

        # email = str(request.POST['email'])
        # password = str(request.POST['password'])
        nik = str(request.POST['nik_pasien'])  
        tanggal_masuk = str(request.POST['tanggal_masuk']) 
        tanggal_keluar = str(request.POST['tanggal_keluar']) 
        kode_rs = str(request.POST['id_kode_rs']) 
        kode_ruangan = str(request.POST['kode_ruangan']) 
        kode_bed = str(request.POST['kode_bed']) 
            
        cursor = connection.cursor()
        cursor.execute("set search_path to siruco")
        cursor.execute("insert into reservasi_rs values ('"+nik+ "','" +tanggal_masuk+ "','" +tanggal_keluar+ "','" +kode_rs+ "','" +kode_ruangan+ "','" +kode_bed+ "')") 
        cursor.execute("set search_path to public")
        cursor.close()
            
        return redirect('trigger_3:list_reservasi_rs')
        

    else:
        formulir = FormReservasiRS()
        dict_kodehotel = {}
        dict_kodehotel2 = {}
        cursor = connection.cursor()
        cursor.execute("set search_path to siruco")
        cursor.execute("select distinct koders from ruangan_rs") # ambil kode rs dari ruangan_rs
        kode_rs = namedtuplefetchall(cursor) #isinya semua koders pada table ruangan rs
        
        # untuk mengirim data kode ruangan ke javascript
        for kode in kode_rs:
            list_temp = []
            cursor.execute("select koderuangan from ruangan_rs where koders = '"+kode.koders+"'")
            list_koderoom = namedtuplefetchall(cursor)
            for koderoom in list_koderoom:
                list_temp.append(koderoom.koderuangan)
            
            dict_kodehotel[kode.koders] = list_temp
        
        dataJSON = dumps(dict_kodehotel)
        #########################################
        
        #list nik
        cursor.execute("select * from pasien") 
        hasil4 = namedtuplefetchall(cursor)
        list_nik = []
        for x in range (len(hasil4)):
            list_nik.append(hasil4[x].nik)

        #list koders
        cursor.execute("select * from rumah_sakit") 
        hasil5 = namedtuplefetchall(cursor)
        list_koders = []
        for x in range (len(hasil5)):
            list_koders.append(hasil5[x].kode_faskes)

        # untuk mengirim data kode bed ke javascript
        for kode in kode_rs:
            list_temp = []
            cursor.execute("select kodebed from bed_rs where koders = '"+kode.koders+"'")
            list_kodebed = namedtuplefetchall(cursor)
            for kodebed in list_kodebed:
                list_temp.append(kodebed.kodebed)
            
            dict_kodehotel2[kode.koders] = list_temp
        
        dataJSON2 = dumps(dict_kodehotel2)
        cursor.execute("set search_path to public")
        cursor.close()
        argument = {    
            'formRS' : formulir,
            'data':dataJSON,
            'data2':dataJSON2,
            'list_nik':list_nik,
            'list_koders':list_koders
        }

    return render(request, 'trigger_3/buat_reservasi_rs.html', argument)

def list_reservasi_rs(request):
    email = request.session['email']
    password = request.session['password']
    cursor = connection.cursor()
    cursor.execute("set search_path to siruco")
    cursor.execute("select * from reservasi_rs")
    hasil = namedtuplefetchall(cursor)
    cursor.execute("select * from akun_pengguna where username='"+email+"' and password='"+password+"'")
    hasil1 = namedtuplefetchall(cursor)
    peran = hasil1[0].peran
    date = datetime.date.today()
    

    cursor.execute("select * from pasien where idpendaftar='"+email+"'")
    hasil2 = namedtuplefetchall(cursor)

    if not len(hasil2):
        nik = None
        hasil3 = None

    else:
        nik = hasil2[0].nik

        cursor.execute("select * from reservasi_rs where kodepasien='"+nik+"'")
        hasil3 = namedtuplefetchall(cursor)
    cursor.execute("set search_path to public")
    cursor.close()
    argument = {
        'table' : hasil,
        'date': date
    }
    
    argument2 = {
        'table' : hasil3,
    }

    if (peran == "Admin_satgas"):
        return render(request, 'trigger_3/list_reservasi_rs.html', argument)
    elif (peran == "Pengguna_publik"):
        return render(request, 'trigger_3/list_reservasi_rs_publik.html', argument2)

def delete_reservasi(request, kodepasien, tglmasuk):
    cursor = connection.cursor()
    cursor.execute("set search_path to siruco")
    cursor.execute("delete from reservasi_rs where kodepasien= '" +kodepasien+"' and tglmasuk = '"+tglmasuk+"'")
    cursor.execute("set search_path to public")
    cursor.close()
    return redirect('trigger_3:list_reservasi_rs')

def update_reservasi(request, kodepasien, tglmasuk):
    # karena yang bisa akses url ini pada navbar hanya admin satgas jadi gak perlu bedain peran
    if request.method == "POST":
        formulir = FormUpdateReservasiRS(request.POST)
        
        tanggal_keluar = str(request.POST['tanggal_keluar']) 
        
        print(tanggal_keluar)
        cursor = connection.cursor()
        cursor.execute("set search_path to siruco")
        cursor.execute("update reservasi_rs set tglkeluar = '"+tanggal_keluar+"' where kodepasien ='"+kodepasien+"' and tglmasuk = '"+tglmasuk+"'") 
        cursor.execute("set search_path to public")
        cursor.close()
            
        return redirect('trigger_3:list_reservasi_rs')
        

    else:
        
        cursor = connection.cursor()
        cursor.execute("set search_path to siruco")
        cursor.execute("select * from reservasi_rs where kodepasien='"+kodepasien+"' and tglmasuk = '"+tglmasuk+"'")
        hasil = namedtuplefetchall(cursor)
        tgl_keluar = hasil[0].tglkeluar
        tanggal_keluar = {
            'tanggal_keluar':tgl_keluar
        }
        print(tanggal_keluar)
        kodepasien = hasil[0].kodepasien
        tglmasuk = hasil[0].tglmasuk
        koders = hasil[0].koders
        koderuangan = hasil[0].koderuangan
        kodebed = hasil[0].kodebed
        formulir = FormUpdateReservasiRS(initial=tanggal_keluar)
        cursor.execute("set search_path to public")
        cursor.close()
        argument = {
            'form':formulir,
            'kodepasien': kodepasien,
            'tglmasuk': tglmasuk,
            'koders': koders,
            'koderuangan': koderuangan,
            'kodebed': kodebed,
            'tglkeluar': tanggal_keluar,
        }
        print(hasil)
        return render(request, 'trigger_3/update_reservasi_rs.html', argument)

def buat_faskes(request):
    # karena yang bisa akses url ini pada navbar hanya admin satgas jadi gak perlu bedain peran
    if request.method == "POST":
        formulir = FormFaskes(request.POST)
        cursor = connection.cursor()
        cursor.execute("set search_path to siruco")
        cursor.execute("SELECT * FROM faskes ORDER BY kode DESC LIMIT 1")
        last_data = dictfetchall(cursor)
        last_no_kode = last_data[0]['kode']
        updated_last_no_kode = int(last_no_kode[1:])+1
        updated_last_no_kode_str = '{:01d}'.format(updated_last_no_kode)
        no_kode = 'Y' + updated_last_no_kode_str
        tipe = str(request.POST['tipe']) 
        nama_faskes = str(request.POST['nama_faskes'])
        status_kepemilikan = str(request.POST['status_kepemilikan'])
        jalan = str(request.POST['jalan'])
        kelurahan = str(request.POST['kelurahan'])
        kecamatan = str(request.POST['kecamatan'])
        kabupaten_kota = str(request.POST['kabupaten_kota'])
        provinsi = str(request.POST['provinsi'])

        
        cursor.execute("insert into faskes values ('"+no_kode+ "','" +tipe+ "','" +nama_faskes+ "','" +status_kepemilikan+ "','" +jalan+ "','" +kelurahan+ "','" +kecamatan+ "','" +kabupaten_kota+ "','" +provinsi+ "')")
        cursor.execute("set search_path to public")
        cursor.close()
            
        return redirect('trigger_3:list-faskes')
        

    else:
        
        formulir = FormFaskes()
        cursor = connection.cursor()
        cursor.execute("set search_path to siruco")
        cursor.execute("SELECT * FROM faskes ORDER BY kode DESC LIMIT 1")
        last_data = dictfetchall(cursor)
        last_no_kode = last_data[0]['kode']
        updated_last_no_kode = int(last_no_kode[1:])+1
        updated_last_no_kode_str = '{:01d}'.format(updated_last_no_kode)
        no_kode = 'Y' + updated_last_no_kode_str
        cursor.execute("set search_path to public")
        cursor.close()
        argument = {
            'form':formulir,
            'kode':no_kode
        }
    
    return render(request, 'trigger_3/buat_faskes.html', argument)
    
def list_faskes(request):
    cursor = connection.cursor()
    cursor.execute("set search_path to siruco")
    cursor.execute("select * from faskes")
    hasil = namedtuplefetchall(cursor)
    cursor.execute("set search_path to public")
    cursor.close()
    argument = {
            'table':hasil,
        }

trigger_3/templates/trigger_3/list_jadwal_faskes.html
{% extends 'base-satgas.html' %}
{% load static %}

{% block meta %}
<link rel="stylesheet" href="{% static 'css/trigger_1.css' %}">
<link rel="stylesheet" href="{% static 'main/css/home.css' %}">

{% endblock %}


{% block content %}


<br><br><br><br>
<table class="tablenomor" style="width:100%">
    <tr>
      <th>No.</th>
      <th>Faskes</th>
      <th>Shift</th>
      <th>Tanggal</th>
      
      
    </tr>

    {% for row in table %}
    <tr>
      <td>{{row.rownumber}}</td>
      <td> {{row.kode_faskes}} </td>
      <td> {{row.shift}} </td> 
      <td> {{row.tanggal}} </td> 

    </tr>
    
{% endfor %}
  </table>


{% endblock %}

trigger_3/templates/trigger_3/list_reservasi_rs.html
{% extends 'base-satgas.html' %}
{% load static %}

{% block meta %}
<link rel="stylesheet" href="{% static 'css/trigger_1.css' %}">
<link rel="stylesheet" href="{% static 'main/css/home.css' %}">

{% endblock %}


{% block content %}


<br><br><br><br>
<table class="tablenomor" style="width:100%">
    <tr>
      <th>No.</th>
      <th>NIK Pasien</th>
      <th>Tanggal Masuk</th>
      <th>Tanggal keluar</th>
      <th>Rumah Sakit</th>
      <th>Ruangan</th>
      <th>Bed</th>
      <th>Action</th>
    </tr>

    {% for row in table %}
    <tr>
      <td></td>
      <td> {{row.kodepasien}} </td>
      <td> {{row.tglmasuk}} </td> 
      <td> {{row.tglkeluar}} </td> 
      <td> {{row.koders}} </td> 
      <td> {{row.koderuangan}} </td> 
      <td> {{row.kodebed}} </td> 
      <td> <a class="tombol-update" href="{% url 'trigger_3:update-reservasi-rs' kodepasien=row.kodepasien tglmasuk=row.tglmasuk %}">UPDATE</a></td>
         {% if row.tglmasuk > date %} <!--yang dapat dihapus hanya reservasi yg tglmasuk > tgl sekarang -->
      <td> <a class="tombol-delete" href="{% url 'trigger_3:delete-reservasi-rs' kodepasien=row.kodepasien tglmasuk=row.tglmasuk %}">DELETE</a> </td>
        {% endif %}
    </tr>
    
{% endfor %}
  </table>


{% endblock %}

trigger_3/templates/trigger_3/list_reservasi_rs_publik.html
{% extends 'base-pengguna-publik.html' %}
{% load static %}

{% block meta %}
<link rel="stylesheet" href="{% static 'css/trigger_1.css' %}">
<link rel="stylesheet" href="{% static 'main/css/home.css' %}">

{% endblock %}


{% block content %}


<br><br><br><br>
<table class="tablenomor" style="width:100%">
    <tr>
      <th>No.</th>
      <th>Kode Pasien</th>
      <th>Tanggal Masuk</th>
      <th>Tanggal keluar</th>
      <th>Kode Rumah Sakit</th>
      <th>Kode Ruangan</th>
      <th>Kode Bed</th>
      
    </tr>

    {% for row in table %}
    <tr>
      <td></td>
      <td> {{row.kodepasien}} </td>
      <td> {{row.tglmasuk}} </td> 
      <td> {{row.tglkeluar}} </td> 
      <td> {{row.koders}} </td> 
      <td> {{row.koderuangan}} </td> 
      <td> {{row.kodebed}} </td> 
    </tr>
    
{% endfor %}
  </table>


{% endblock %}

trigger_3/templates/trigger_3/list_rumah_sakit.html
{% extends 'base-satgas.html' %}
{% load static %}

{% block meta %}
<link rel="stylesheet" href="{% static 'css/trigger_1.css' %}">
<link rel="stylesheet" href="{% static 'main/css/home.css' %}">

{% endblock %}


{% block content %}


<br><br><br><br>
<table style="width:100%">
    <tr>
      <th>Kode</th>
      <th>Rujukan?</th>
      <th>Action</th>
      
      
    </tr>
    
    {% for row in daftar %}
    
    <tr>
      <td> {{row.0.kode_faskes}} </td>
      <td> <input type="checkbox" id="checkboxrujukan" {{ row.1 }} disabled> </td>
      <td> <a class="tombol-update" href="{% url 'trigger_3:update-rs' kodefaskes=row.0.kode_faskes %}">UPDATE</a></td>
      
      
    </tr>

{% endfor %}

  </table>


{% endblock %}

trigger_3/templates/trigger_3/list_transaksi_rs.html
{% extends 'base-satgas.html' %}
{% load static %}

{% block meta %}
<link rel="stylesheet" href="{% static 'css/trigger_1.css' %}">
<link rel="stylesheet" href="{% static 'main/css/home.css' %}">

{% endblock %}


{% block content %}


<br><br><br><br>
<table  style="width:100%">
    <tr>
      
      <th>Id Transaksi</th>
      <th>Kode Pasien</th>
      <th>Tanggal Pembayaran</th>
      <th>Waktu Pembayaran</th>
      <th>Tanggal Masuk</th>
      <th>Total Biaya</th>
      <th>Status Bayar</th>
      <th>Action</th>
      
      
    </tr>

    {% for row in table %}
    <tr>
      
      <td> {{row.idtransaksi}} </td>
      <td> {{row.kodepasien}} </td> 
      <td> {{row.tanggalpembayaran}} </td> 
      <td> {{row.waktupembayaran}} </td> 
      <td> {{row.tglmasuk}} </td> 
      <td> {{row.totalbiaya}} </td> 
      <td> {{row.statusbayar}} </td> 
      <td> <a class="tombol-update" href="{% url 'trigger_3:update-transaksi-rs' id=row.idtransaksi %}">UPDATE</a></td>
      <td> <a class="tombol-delete" href="{% url 'trigger_3:delete-transaksi-rs' id=row.idtransaksi %}">DELETE</a> </td>

    </tr>
    
{% endfor %}
  </table>


{% endblock %}

trigger_3/templates/trigger_3/update_faskes.html
{% extends 'base-satgas.html' %}
{% load static %}

{% block meta %}
<link rel="stylesheet" href="{% static 'css/trigger_1.css' %}">
<link rel="stylesheet" href="{% static 'main/css/home.css' %}">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
{% endblock %}

{% block content %}

<script language="javascript" type="text/javascript">
  
  $(document).ready(function () {

    $("#id_kode_rs").change(function () {
      
        var el = $(this);
        var data = JSON.parse("{{data|escapejs}}");  //ngambil data yang di transfer dari views supaya bisa dipake gi js

        var list = document.getElementById("kode_ruangan"); //clear data sebelumnya
        while (list.hasChildNodes()) {
          list.removeChild(list.firstChild);
        }

        const keys = Object.keys(data); // ngambil key-key yang ada dalam bentuk list
        for (i = 0; i < keys.length; i++) {
          if (el.val() == keys[i]) {   
            var temp = data[keys[i]]; //list dari kode room
            for (j = 0; j < temp.length ; j++) {  //masukin optionnya
              $("#kode_ruangan").append("<option>"+temp[j]+"</option>");
              
            }break;
          }
         
        }
        
        var data2 = JSON.parse("{{data2|escapejs}}");  //ngambil data yang di transfer dari views supaya bisa dipake gi js

        var list = document.getElementById("kode_bed"); //clear data sebelumnya
        while (list.hasChildNodes()) {
          list.removeChild(list.firstChild);
        }

        const keys2 = Object.keys(data2); // ngambil key-key yang ada dalam bentuk list
        for (i = 0; i < keys2.length; i++) {
          if (el.val() == keys2[i]) {   
            var temp = data2[keys2[i]]; //list dari kode room
            for (j = 0; j < temp.length ; j++) {  //masukin optionnya
              $("#kode_bed").append("<option>"+temp[j]+"</option>");
              
            }break;
          }
         
        }
       
    });

    });
    
    function Validation()
    {
      var entrydate, outdate;
      entrydate = document.getElementById("id_tanggal_masuk").value;
      outdate = document.getElementById("id_tanggal_keluar").value;
      if(entrydate > outdate)
      
      {
          event.preventDefault();
          alert("Maaf, tolong masukan tanggal keluar > tanggal masuk");
          returnToPreviousPage();
          return false;
      }
      return true;
    }

  </script>


<br><br><br><br>
<section class="home">
    <section class="section2">
      <h3 style="color: red;">{{ pesan }}</h3>
        <div class="parent-card">
            <div class="box-card">
              <h2 class="title">Update FASKES</h2>
              <form method="POST" action="{% url 'trigger_3:update-faskes' kodefaskes=kode %}" onsubmit="Validation();">
                {% csrf_token %}
                <div class="row">
                  <div class="col-25">
                    <label for="nik">
                        Kode Faskes
                    </label>
                  </div>
                  <div class="col-75">
                    {{ kode }}
                  </div>
                </div>
                <div class="row">
                  <div class="col-25">
                    <label for="kode_rs">
                      Tipe
                    </label>
                  </div>
                  <div id = "kode_hotel" class="col-75">
                    {{ form.tipe }}
                  </div>
                </div>

                <div class="row">
                  <div class="col-25">
                    <label for="tanggal_keluar">
                      Nama Faskes
                    </label>
                  </div>
                  <div class="col-75">
                    {{ form.nama_faskes }}
                  </div>
                </div>
                
                <div class="row">
                  <div class="col-25">
                    <label for="kode_rs">
                      Status Kepemilikan
                    </label>
                  </div>
                  <div id = "kode_hotel" class="col-75">
                    {{ form.status_kepemilikan }}
                  </div>
                </div>

                <div class="row">
                  <div class="col-25">
                    <label for="tanggal_keluar">
                      Alamat:
                    </label>
                  </div>
                  <div class="col-75">
                    
                  </div>
                </div>
                
                <div class="row">
                  <div class="col-25">
                    <label for="tanggal_keluar">
                      Jalan
                    </label>
                  </div>
                  <div class="col-75">
                    {{ form.jalan }}
                  </div>
                </div>

                <div class="row">
                  <div class="col-25">
                    <label for="tanggal_keluar">
                      Kelurahan
                    </label>
                  </div>
                  <div class="col-75">
                    {{ form.kelurahan }}
                  </div>
                </div>

                <div class="row">
                  <div class="col-25">
                    <label for="tanggal_keluar">
                      Kecamatan
                    </label>
                  </div>
                  <div class="col-75">
                    {{ form.kecamatan }}
                  </div>
                </div>

                <div class="row">
                  <div class="col-25">
                    <label for="tanggal_keluar">
                      Kabupaten/Kota
                    </label>
                  </div>
                  <div class="col-75">
                    {{ form.kabupaten_kota }}
                  </div>
                </div>

                <div class="row">
                  <div class="col-25">
                    <label for="tanggal_keluar">
                      Provinsi
                    </label>
                  </div>
                  <div class="col-75">
                    {{ form.provinsi }}
                  </div>
                </div>

                <div class="row">
                  <input type="submit" value="Simpan">
                </div>
              </form>
            </div>
     
        </div>
    </section>
  </section>



{% endblock %}